// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"turn-inspector/ent/run"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Run is the model entity for the Run schema.
type Run struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RunQuery when eager-loading is set.
	Edges        RunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RunEdges holds the relations/edges for other nodes in the graph.
type RunEdges struct {
	// Turns holds the value of the turns edge.
	Turns []*Turn `json:"turns,omitempty"`
	// Metadata holds the value of the metadata edge.
	Metadata []*RunMetadata `json:"metadata,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TurnsOrErr returns the Turns value or an error if the edge
// was not loaded in eager-loading.
func (e RunEdges) TurnsOrErr() ([]*Turn, error) {
	if e.loadedTypes[0] {
		return e.Turns, nil
	}
	return nil, &NotLoadedError{edge: "turns"}
}

// MetadataOrErr returns the Metadata value or an error if the edge
// was not loaded in eager-loading.
func (e RunEdges) MetadataOrErr() ([]*RunMetadata, error) {
	if e.loadedTypes[1] {
		return e.Metadata, nil
	}
	return nil, &NotLoadedError{edge: "metadata"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Run) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			values[i] = new(sql.NullInt64)
		case run.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Run fields.
func (_m *Run) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case run.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Run.
// This includes values selected through modifiers, order, etc.
func (_m *Run) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTurns queries the "turns" edge of the Run entity.
func (_m *Run) QueryTurns() *TurnQuery {
	return NewRunClient(_m.config).QueryTurns(_m)
}

// QueryMetadata queries the "metadata" edge of the Run entity.
func (_m *Run) QueryMetadata() *RunMetadataQuery {
	return NewRunClient(_m.config).QueryMetadata(_m)
}

// Update returns a builder for updating this Run.
// Note that you need to call Run.Unwrap() before calling this method if this Run
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Run) Update() *RunUpdateOne {
	return NewRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Run entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Run) Unwrap() *Run {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Run is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Run) String() string {
	var builder strings.Builder
	builder.WriteString("Run(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Runs is a parsable slice of Run.
type Runs []*Run
