// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"turn-inspector/ent/predicate"
	"turn-inspector/ent/turn"
	"turn-inspector/ent/turnmetadata"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TurnMetadataQuery is the builder for querying TurnMetadata entities.
type TurnMetadataQuery struct {
	config
	ctx        *QueryContext
	order      []turnmetadata.OrderOption
	inters     []Interceptor
	predicates []predicate.TurnMetadata
	withTurn   *TurnQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TurnMetadataQuery builder.
func (_q *TurnMetadataQuery) Where(ps ...predicate.TurnMetadata) *TurnMetadataQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TurnMetadataQuery) Limit(limit int) *TurnMetadataQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TurnMetadataQuery) Offset(offset int) *TurnMetadataQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TurnMetadataQuery) Unique(unique bool) *TurnMetadataQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TurnMetadataQuery) Order(o ...turnmetadata.OrderOption) *TurnMetadataQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTurn chains the current query on the "turn" edge.
func (_q *TurnMetadataQuery) QueryTurn() *TurnQuery {
	query := (&TurnClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(turnmetadata.Table, turnmetadata.FieldID, selector),
			sqlgraph.To(turn.Table, turn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, turnmetadata.TurnTable, turnmetadata.TurnColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TurnMetadata entity from the query.
// Returns a *NotFoundError when no TurnMetadata was found.
func (_q *TurnMetadataQuery) First(ctx context.Context) (*TurnMetadata, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{turnmetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TurnMetadataQuery) FirstX(ctx context.Context) *TurnMetadata {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TurnMetadata ID from the query.
// Returns a *NotFoundError when no TurnMetadata ID was found.
func (_q *TurnMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{turnmetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TurnMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TurnMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TurnMetadata entity is found.
// Returns a *NotFoundError when no TurnMetadata entities are found.
func (_q *TurnMetadataQuery) Only(ctx context.Context) (*TurnMetadata, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{turnmetadata.Label}
	default:
		return nil, &NotSingularError{turnmetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TurnMetadataQuery) OnlyX(ctx context.Context) *TurnMetadata {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TurnMetadata ID in the query.
// Returns a *NotSingularError when more than one TurnMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TurnMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{turnmetadata.Label}
	default:
		err = &NotSingularError{turnmetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TurnMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TurnMetadataSlice.
func (_q *TurnMetadataQuery) All(ctx context.Context) ([]*TurnMetadata, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TurnMetadata, *TurnMetadataQuery]()
	return withInterceptors[[]*TurnMetadata](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TurnMetadataQuery) AllX(ctx context.Context) []*TurnMetadata {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TurnMetadata IDs.
func (_q *TurnMetadataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(turnmetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TurnMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TurnMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TurnMetadataQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TurnMetadataQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TurnMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TurnMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TurnMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TurnMetadataQuery) Clone() *TurnMetadataQuery {
	if _q == nil {
		return nil
	}
	return &TurnMetadataQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]turnmetadata.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.TurnMetadata{}, _q.predicates...),
		withTurn:   _q.withTurn.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTurn tells the query-builder to eager-load the nodes that are connected to
// the "turn" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TurnMetadataQuery) WithTurn(opts ...func(*TurnQuery)) *TurnMetadataQuery {
	query := (&TurnClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTurn = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TurnMetadata.Query().
//		GroupBy(turnmetadata.FieldSource).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TurnMetadataQuery) GroupBy(field string, fields ...string) *TurnMetadataGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TurnMetadataGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = turnmetadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//	}
//
//	client.TurnMetadata.Query().
//		Select(turnmetadata.FieldSource).
//		Scan(ctx, &v)
func (_q *TurnMetadataQuery) Select(fields ...string) *TurnMetadataSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TurnMetadataSelect{TurnMetadataQuery: _q}
	sbuild.label = turnmetadata.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TurnMetadataSelect configured with the given aggregations.
func (_q *TurnMetadataQuery) Aggregate(fns ...AggregateFunc) *TurnMetadataSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TurnMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !turnmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TurnMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TurnMetadata, error) {
	var (
		nodes       = []*TurnMetadata{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withTurn != nil,
		}
	)
	if _q.withTurn != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, turnmetadata.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TurnMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TurnMetadata{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTurn; query != nil {
		if err := _q.loadTurn(ctx, query, nodes, nil,
			func(n *TurnMetadata, e *Turn) { n.Edges.Turn = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TurnMetadataQuery) loadTurn(ctx context.Context, query *TurnQuery, nodes []*TurnMetadata, init func(*TurnMetadata), assign func(*TurnMetadata, *Turn)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TurnMetadata)
	for i := range nodes {
		if nodes[i].turn_metadata == nil {
			continue
		}
		fk := *nodes[i].turn_metadata
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(turn.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "turn_metadata" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TurnMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TurnMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(turnmetadata.Table, turnmetadata.Columns, sqlgraph.NewFieldSpec(turnmetadata.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, turnmetadata.FieldID)
		for i := range fields {
			if fields[i] != turnmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TurnMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(turnmetadata.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = turnmetadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TurnMetadataGroupBy is the group-by builder for TurnMetadata entities.
type TurnMetadataGroupBy struct {
	selector
	build *TurnMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TurnMetadataGroupBy) Aggregate(fns ...AggregateFunc) *TurnMetadataGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TurnMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TurnMetadataQuery, *TurnMetadataGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TurnMetadataGroupBy) sqlScan(ctx context.Context, root *TurnMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TurnMetadataSelect is the builder for selecting fields of TurnMetadata entities.
type TurnMetadataSelect struct {
	*TurnMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TurnMetadataSelect) Aggregate(fns ...AggregateFunc) *TurnMetadataSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TurnMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TurnMetadataQuery, *TurnMetadataSelect](ctx, _s.TurnMetadataQuery, _s, _s.inters, v)
}

func (_s *TurnMetadataSelect) sqlScan(ctx context.Context, root *TurnMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
