// Code generated by ent, DO NOT EDIT.

package goat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/farm/goat-manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Goat {
	return predicate.Goat(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Goat {
	return predicate.Goat(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldName, v))
}

// BirthDate applies equality check predicate on the "birth_date" field. It's identical to BirthDateEQ.
func BirthDate(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldBirthDate, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldWeight, v))
}

// SireTag applies equality check predicate on the "sire_tag" field. It's identical to SireTagEQ.
func SireTag(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldSireTag, v))
}

// DamTag applies equality check predicate on the "dam_tag" field. It's identical to DamTagEQ.
func DamTag(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldDamTag, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContainsFold(FieldName, v))
}

// BreedEQ applies the EQ predicate on the "breed" field.
func BreedEQ(v Breed) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldBreed, v))
}

// BreedNEQ applies the NEQ predicate on the "breed" field.
func BreedNEQ(v Breed) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldBreed, v))
}

// BreedIn applies the In predicate on the "breed" field.
func BreedIn(vs ...Breed) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldBreed, vs...))
}

// BreedNotIn applies the NotIn predicate on the "breed" field.
func BreedNotIn(vs ...Breed) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldBreed, vs...))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v Gender) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v Gender) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...Gender) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...Gender) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldGender, vs...))
}

// BirthDateEQ applies the EQ predicate on the "birth_date" field.
func BirthDateEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldBirthDate, v))
}

// BirthDateNEQ applies the NEQ predicate on the "birth_date" field.
func BirthDateNEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldBirthDate, v))
}

// BirthDateIn applies the In predicate on the "birth_date" field.
func BirthDateIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldBirthDate, vs...))
}

// BirthDateNotIn applies the NotIn predicate on the "birth_date" field.
func BirthDateNotIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldBirthDate, vs...))
}

// BirthDateGT applies the GT predicate on the "birth_date" field.
func BirthDateGT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldBirthDate, v))
}

// BirthDateGTE applies the GTE predicate on the "birth_date" field.
func BirthDateGTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldBirthDate, v))
}

// BirthDateLT applies the LT predicate on the "birth_date" field.
func BirthDateLT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldBirthDate, v))
}

// BirthDateLTE applies the LTE predicate on the "birth_date" field.
func BirthDateLTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldBirthDate, v))
}

// BirthDateIsNil applies the IsNil predicate on the "birth_date" field.
func BirthDateIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldBirthDate))
}

// BirthDateNotNil applies the NotNil predicate on the "birth_date" field.
func BirthDateNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldBirthDate))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldWeight, v))
}

// WeightIsNil applies the IsNil predicate on the "weight" field.
func WeightIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldWeight))
}

// WeightNotNil applies the NotNil predicate on the "weight" field.
func WeightNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldWeight))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldStatus, vs...))
}

// SireTagEQ applies the EQ predicate on the "sire_tag" field.
func SireTagEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldSireTag, v))
}

// SireTagNEQ applies the NEQ predicate on the "sire_tag" field.
func SireTagNEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldSireTag, v))
}

// SireTagIn applies the In predicate on the "sire_tag" field.
func SireTagIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldSireTag, vs...))
}

// SireTagNotIn applies the NotIn predicate on the "sire_tag" field.
func SireTagNotIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldSireTag, vs...))
}

// SireTagGT applies the GT predicate on the "sire_tag" field.
func SireTagGT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldSireTag, v))
}

// SireTagGTE applies the GTE predicate on the "sire_tag" field.
func SireTagGTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldSireTag, v))
}

// SireTagLT applies the LT predicate on the "sire_tag" field.
func SireTagLT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldSireTag, v))
}

// SireTagLTE applies the LTE predicate on the "sire_tag" field.
func SireTagLTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldSireTag, v))
}

// SireTagContains applies the Contains predicate on the "sire_tag" field.
func SireTagContains(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContains(FieldSireTag, v))
}

// SireTagHasPrefix applies the HasPrefix predicate on the "sire_tag" field.
func SireTagHasPrefix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasPrefix(FieldSireTag, v))
}

// SireTagHasSuffix applies the HasSuffix predicate on the "sire_tag" field.
func SireTagHasSuffix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasSuffix(FieldSireTag, v))
}

// SireTagIsNil applies the IsNil predicate on the "sire_tag" field.
func SireTagIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldSireTag))
}

// SireTagNotNil applies the NotNil predicate on the "sire_tag" field.
func SireTagNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldSireTag))
}

// SireTagEqualFold applies the EqualFold predicate on the "sire_tag" field.
func SireTagEqualFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEqualFold(FieldSireTag, v))
}

// SireTagContainsFold applies the ContainsFold predicate on the "sire_tag" field.
func SireTagContainsFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContainsFold(FieldSireTag, v))
}

// DamTagEQ applies the EQ predicate on the "dam_tag" field.
func DamTagEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldDamTag, v))
}

// DamTagNEQ applies the NEQ predicate on the "dam_tag" field.
func DamTagNEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldDamTag, v))
}

// DamTagIn applies the In predicate on the "dam_tag" field.
func DamTagIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldDamTag, vs...))
}

// DamTagNotIn applies the NotIn predicate on the "dam_tag" field.
func DamTagNotIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldDamTag, vs...))
}

// DamTagGT applies the GT predicate on the "dam_tag" field.
func DamTagGT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldDamTag, v))
}

// DamTagGTE applies the GTE predicate on the "dam_tag" field.
func DamTagGTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldDamTag, v))
}

// DamTagLT applies the LT predicate on the "dam_tag" field.
func DamTagLT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldDamTag, v))
}

// DamTagLTE applies the LTE predicate on the "dam_tag" field.
func DamTagLTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldDamTag, v))
}

// DamTagContains applies the Contains predicate on the "dam_tag" field.
func DamTagContains(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContains(FieldDamTag, v))
}

// DamTagHasPrefix applies the HasPrefix predicate on the "dam_tag" field.
func DamTagHasPrefix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasPrefix(FieldDamTag, v))
}

// DamTagHasSuffix applies the HasSuffix predicate on the "dam_tag" field.
func DamTagHasSuffix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasSuffix(FieldDamTag, v))
}

// DamTagIsNil applies the IsNil predicate on the "dam_tag" field.
func DamTagIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldDamTag))
}

// DamTagNotNil applies the NotNil predicate on the "dam_tag" field.
func DamTagNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldDamTag))
}

// DamTagEqualFold applies the EqualFold predicate on the "dam_tag" field.
func DamTagEqualFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEqualFold(FieldDamTag, v))
}

// DamTagContainsFold applies the ContainsFold predicate on the "dam_tag" field.
func DamTagContainsFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContainsFold(FieldDamTag, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Goat {
	return predicate.Goat(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Goat {
	return predicate.Goat(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Goat {
	return predicate.Goat(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Goat {
	return predicate.Goat(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Goat {
	return predicate.Goat(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMilkRecords applies the HasEdge predicate on the "milk_records" edge.
func HasMilkRecords() predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MilkRecordsTable, MilkRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMilkRecordsWith applies the HasEdge predicate on the "milk_records" edge with a given conditions (other predicates).
func HasMilkRecordsWith(preds ...predicate.MilkRecord) predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := newMilkRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHealthRecords applies the HasEdge predicate on the "health_records" edge.
func HasHealthRecords() predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HealthRecordsTable, HealthRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHealthRecordsWith applies the HasEdge predicate on the "health_records" edge with a given conditions (other predicates).
func HasHealthRecordsWith(preds ...predicate.HealthRecord) predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := newHealthRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBreedingRecords applies the HasEdge predicate on the "breeding_records" edge.
func HasBreedingRecords() predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BreedingRecordsTable, BreedingRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBreedingRecordsWith applies the HasEdge predicate on the "breeding_records" edge with a given conditions (other predicates).
func HasBreedingRecordsWith(preds ...predicate.BreedingRecord) predicate.Goat {
	return predicate.Goat(func(s *sql.Selector) {
		step := newBreedingRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Goat) predicate.Goat {
	return predicate.Goat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Goat) predicate.Goat {
	return predicate.Goat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Goat) predicate.Goat {
	return predicate.Goat(sql.NotPredicates(p))
}
