version: "2"


linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1008" # could remove embedded field selector

  enable:
    # Enable a basic set of useful linters
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - errcheck
    # Add other linters you want to enable

run:
  # Timeout for analysis, e.g., 5 minutes
  timeout: 5m 