# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order.proto", :syntax => :proto3) do
    add_message "order.OrderCreated" do
      optional :order_id, :string, 1
      optional :user_id, :string, 2
      repeated :items, :message, 3, "order.OrderItem"
      optional :total_amount, :float, 4
      optional :timestamp, :string, 5
    end
    add_message "order.PaymentProcessed" do
      optional :order_id, :string, 1
      optional :payment_id, :string, 2
      optional :status, :string, 3
      optional :transaction_id, :string, 4
      optional :amount, :float, 5
      optional :timestamp, :string, 6
    end
    add_message "order.InventoryChecked" do
      optional :order_id, :string, 1
      optional :all_items_available, :bool, 2
      repeated :unavailable_items, :message, 3, "order.UnavailableItem"
      optional :timestamp, :string, 4
    end
    add_message "order.OrderFulfilled" do
      optional :order_id, :string, 1
      optional :shipping_id, :string, 2
      optional :tracking_number, :string, 3
      optional :status, :string, 4
      optional :timestamp, :string, 5
    end
    add_message "order.OrderCancelled" do
      optional :order_id, :string, 1
      optional :reason, :string, 2
      optional :refund_status, :string, 3
      optional :timestamp, :string, 4
    end
    add_message "order.Notification" do
      optional :order_id, :string, 1
      optional :notification_type, :string, 2
      optional :recipient, :string, 3
      optional :content, :string, 4
      optional :timestamp, :string, 5
    end
    add_message "order.OrderItem" do
      optional :product_id, :string, 1
      optional :name, :string, 2
      optional :quantity, :int32, 3
      optional :price, :float, 4
    end
    add_message "order.UnavailableItem" do
      optional :product_id, :string, 1
      optional :name, :string, 2
      optional :requested_quantity, :int32, 3
      optional :available_quantity, :int32, 4
    end
    add_message "order.SagaEvent" do
      optional :saga_id, :string, 1
      optional :saga_name, :string, 2
      optional :status, :string, 3
      optional :timestamp, :int64, 4
      optional :error, :string, 5
    end
  end
end

module KafkaWatermill
  module IDL
    OrderCreated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.OrderCreated").msgclass
    PaymentProcessed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.PaymentProcessed").msgclass
    InventoryChecked = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.InventoryChecked").msgclass
    OrderFulfilled = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.OrderFulfilled").msgclass
    OrderCancelled = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.OrderCancelled").msgclass
    Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.Notification").msgclass
    OrderItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.OrderItem").msgclass
    UnavailableItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.UnavailableItem").msgclass
    SagaEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.SagaEvent").msgclass
  end
end
