// Code generated by ent, DO NOT EDIT.

package feedrecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the feedrecord type in the database.
	Label = "feed_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFeedingDate holds the string denoting the feeding_date field in the database.
	FieldFeedingDate = "feeding_date"
	// FieldFeedType holds the string denoting the feed_type field in the database.
	FieldFeedType = "feed_type"
	// FieldFeedName holds the string denoting the feed_name field in the database.
	FieldFeedName = "feed_name"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldGoatTags holds the string denoting the goat_tags field in the database.
	FieldGoatTags = "goat_tags"
	// FieldFeedingMethod holds the string denoting the feeding_method field in the database.
	FieldFeedingMethod = "feeding_method"
	// FieldFedBy holds the string denoting the fed_by field in the database.
	FieldFedBy = "fed_by"
	// FieldCostPerUnit holds the string denoting the cost_per_unit field in the database.
	FieldCostPerUnit = "cost_per_unit"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the feedrecord in the database.
	Table = "feed_records"
)

// Columns holds all SQL columns for feedrecord fields.
var Columns = []string{
	FieldID,
	FieldFeedingDate,
	FieldFeedType,
	FieldFeedName,
	FieldQuantity,
	FieldUnit,
	FieldGoatTags,
	FieldFeedingMethod,
	FieldFedBy,
	FieldCostPerUnit,
	FieldNotes,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFeedingDate holds the default value on creation for the "feeding_date" field.
	DefaultFeedingDate func() time.Time
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(float64) error
	// CostPerUnitValidator is a validator for the "cost_per_unit" field. It is called by the builders before save.
	CostPerUnitValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// FeedType defines the type for the "feed_type" enum field.
type FeedType string

// FeedType values.
const (
	FeedTypeHay         FeedType = "hay"
	FeedTypeGrain       FeedType = "grain"
	FeedTypePellets     FeedType = "pellets"
	FeedTypePasture     FeedType = "pasture"
	FeedTypeSilage      FeedType = "silage"
	FeedTypeSupplements FeedType = "supplements"
	FeedTypeTreats      FeedType = "treats"
	FeedTypeOther       FeedType = "other"
)

func (ft FeedType) String() string {
	return string(ft)
}

// FeedTypeValidator is a validator for the "feed_type" field enum values. It is called by the builders before save.
func FeedTypeValidator(ft FeedType) error {
	switch ft {
	case FeedTypeHay, FeedTypeGrain, FeedTypePellets, FeedTypePasture, FeedTypeSilage, FeedTypeSupplements, FeedTypeTreats, FeedTypeOther:
		return nil
	default:
		return fmt.Errorf("feedrecord: invalid enum value for feed_type field: %q", ft)
	}
}

// Unit defines the type for the "unit" enum field.
type Unit string

// UnitKg is the default value of the Unit enum.
const DefaultUnit = UnitKg

// Unit values.
const (
	UnitKg     Unit = "kg"
	UnitLbs    Unit = "lbs"
	UnitCups   Unit = "cups"
	UnitScoops Unit = "scoops"
	UnitBales  Unit = "bales"
)

func (u Unit) String() string {
	return string(u)
}

// UnitValidator is a validator for the "unit" field enum values. It is called by the builders before save.
func UnitValidator(u Unit) error {
	switch u {
	case UnitKg, UnitLbs, UnitCups, UnitScoops, UnitBales:
		return nil
	default:
		return fmt.Errorf("feedrecord: invalid enum value for unit field: %q", u)
	}
}

// FeedingMethod defines the type for the "feeding_method" enum field.
type FeedingMethod string

// FeedingMethodGroup is the default value of the FeedingMethod enum.
const DefaultFeedingMethod = FeedingMethodGroup

// FeedingMethod values.
const (
	FeedingMethodIndividual FeedingMethod = "individual"
	FeedingMethodGroup      FeedingMethod = "group"
	FeedingMethodPasture    FeedingMethod = "pasture"
)

func (fm FeedingMethod) String() string {
	return string(fm)
}

// FeedingMethodValidator is a validator for the "feeding_method" field enum values. It is called by the builders before save.
func FeedingMethodValidator(fm FeedingMethod) error {
	switch fm {
	case FeedingMethodIndividual, FeedingMethodGroup, FeedingMethodPasture:
		return nil
	default:
		return fmt.Errorf("feedrecord: invalid enum value for feeding_method field: %q", fm)
	}
}

// OrderOption defines the ordering options for the FeedRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFeedingDate orders the results by the feeding_date field.
func ByFeedingDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedingDate, opts...).ToFunc()
}

// ByFeedType orders the results by the feed_type field.
func ByFeedType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedType, opts...).ToFunc()
}

// ByFeedName orders the results by the feed_name field.
func ByFeedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedName, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByGoatTags orders the results by the goat_tags field.
func ByGoatTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoatTags, opts...).ToFunc()
}

// ByFeedingMethod orders the results by the feeding_method field.
func ByFeedingMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedingMethod, opts...).ToFunc()
}

// ByFedBy orders the results by the fed_by field.
func ByFedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFedBy, opts...).ToFunc()
}

// ByCostPerUnit orders the results by the cost_per_unit field.
func ByCostPerUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPerUnit, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
