// Code generated by ent, DO NOT EDIT.

package block

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the block type in the database.
	Label = "block"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// EdgeTurn holds the string denoting the turn edge name in mutations.
	EdgeTurn = "turn"
	// EdgeMetadata holds the string denoting the metadata edge name in mutations.
	EdgeMetadata = "metadata"
	// Table holds the table name of the block in the database.
	Table = "blocks"
	// TurnTable is the table that holds the turn relation/edge.
	TurnTable = "blocks"
	// TurnInverseTable is the table name for the Turn entity.
	// It exists in this package in order to avoid circular dependency with the "turn" package.
	TurnInverseTable = "turns"
	// TurnColumn is the table column denoting the turn relation/edge.
	TurnColumn = "turn_blocks"
	// MetadataTable is the table that holds the metadata relation/edge.
	MetadataTable = "block_metadata"
	// MetadataInverseTable is the table name for the BlockMetadata entity.
	// It exists in this package in order to avoid circular dependency with the "blockmetadata" package.
	MetadataInverseTable = "block_metadata"
	// MetadataColumn is the table column denoting the metadata relation/edge.
	MetadataColumn = "block_metadata"
)

// Columns holds all SQL columns for block fields.
var Columns = []string{
	FieldID,
	FieldOrder,
	FieldKind,
	FieldRole,
	FieldPayload,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "blocks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"turn_blocks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindLlmText  Kind = "llm_text"
	KindToolCall Kind = "tool_call"
	KindToolUse  Kind = "tool_use"
	KindSystem   Kind = "system"
	KindUser     Kind = "user"
	KindOther    Kind = "other"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindLlmText, KindToolCall, KindToolUse, KindSystem, KindUser, KindOther:
		return nil
	default:
		return fmt.Errorf("block: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Block queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByTurnField orders the results by turn field.
func ByTurnField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTurnStep(), sql.OrderByField(field, opts...))
	}
}

// ByMetadataCount orders the results by metadata count.
func ByMetadataCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMetadataStep(), opts...)
	}
}

// ByMetadata orders the results by metadata terms.
func ByMetadata(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMetadataStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTurnStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TurnInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TurnTable, TurnColumn),
	)
}
func newMetadataStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MetadataInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MetadataTable, MetadataColumn),
	)
}
