// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/breedingrecord"
	"github.com/farm/goat-manager/ent/predicate"
)

// BreedingRecordDelete is the builder for deleting a BreedingRecord entity.
type BreedingRecordDelete struct {
	config
	hooks    []Hook
	mutation *BreedingRecordMutation
}

// Where appends a list predicates to the BreedingRecordDelete builder.
func (_d *BreedingRecordDelete) Where(ps ...predicate.BreedingRecord) *BreedingRecordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BreedingRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BreedingRecordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BreedingRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(breedingrecord.Table, sqlgraph.NewFieldSpec(breedingrecord.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BreedingRecordDeleteOne is the builder for deleting a single BreedingRecord entity.
type BreedingRecordDeleteOne struct {
	_d *BreedingRecordDelete
}

// Where appends a list predicates to the BreedingRecordDelete builder.
func (_d *BreedingRecordDeleteOne) Where(ps ...predicate.BreedingRecord) *BreedingRecordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BreedingRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{breedingrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BreedingRecordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
