// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/farm/goat-manager/ent/farmoperation"
)

// FarmOperation is the model entity for the FarmOperation schema.
type FarmOperation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date of the farm operation
	OperationDate time.Time `json:"operation_date,omitempty"`
	// Type of farm operation
	OperationType farmoperation.OperationType `json:"operation_type,omitempty"`
	// Description of the operation performed
	Description string `json:"description,omitempty"`
	// Person who performed the operation
	PerformedBy string `json:"performed_by,omitempty"`
	// Comma-separated list of goat tags affected by this operation
	AffectedGoats string `json:"affected_goats,omitempty"`
	// Quantity involved (feed amount, milk volume, etc.)
	Quantity float64 `json:"quantity,omitempty"`
	// Unit of measurement for quantity
	Unit string `json:"unit,omitempty"`
	// Cost associated with the operation
	Cost float64 `json:"cost,omitempty"`
	// Revenue generated from the operation
	Revenue float64 `json:"revenue,omitempty"`
	// Supplier or buyer involved in the operation
	SupplierBuyer string `json:"supplier_buyer,omitempty"`
	// Additional notes about the operation
	Notes string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FarmOperation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case farmoperation.FieldQuantity, farmoperation.FieldCost, farmoperation.FieldRevenue:
			values[i] = new(sql.NullFloat64)
		case farmoperation.FieldID:
			values[i] = new(sql.NullInt64)
		case farmoperation.FieldOperationType, farmoperation.FieldDescription, farmoperation.FieldPerformedBy, farmoperation.FieldAffectedGoats, farmoperation.FieldUnit, farmoperation.FieldSupplierBuyer, farmoperation.FieldNotes:
			values[i] = new(sql.NullString)
		case farmoperation.FieldOperationDate, farmoperation.FieldCreatedAt, farmoperation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FarmOperation fields.
func (_m *FarmOperation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case farmoperation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case farmoperation.FieldOperationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field operation_date", values[i])
			} else if value.Valid {
				_m.OperationDate = value.Time
			}
		case farmoperation.FieldOperationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_type", values[i])
			} else if value.Valid {
				_m.OperationType = farmoperation.OperationType(value.String)
			}
		case farmoperation.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case farmoperation.FieldPerformedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field performed_by", values[i])
			} else if value.Valid {
				_m.PerformedBy = value.String
			}
		case farmoperation.FieldAffectedGoats:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field affected_goats", values[i])
			} else if value.Valid {
				_m.AffectedGoats = value.String
			}
		case farmoperation.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case farmoperation.FieldUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit", values[i])
			} else if value.Valid {
				_m.Unit = value.String
			}
		case farmoperation.FieldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = value.Float64
			}
		case farmoperation.FieldRevenue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field revenue", values[i])
			} else if value.Valid {
				_m.Revenue = value.Float64
			}
		case farmoperation.FieldSupplierBuyer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_buyer", values[i])
			} else if value.Valid {
				_m.SupplierBuyer = value.String
			}
		case farmoperation.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case farmoperation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case farmoperation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FarmOperation.
// This includes values selected through modifiers, order, etc.
func (_m *FarmOperation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FarmOperation.
// Note that you need to call FarmOperation.Unwrap() before calling this method if this FarmOperation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FarmOperation) Update() *FarmOperationUpdateOne {
	return NewFarmOperationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FarmOperation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FarmOperation) Unwrap() *FarmOperation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FarmOperation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FarmOperation) String() string {
	var builder strings.Builder
	builder.WriteString("FarmOperation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("operation_date=")
	builder.WriteString(_m.OperationDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("operation_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperationType))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("performed_by=")
	builder.WriteString(_m.PerformedBy)
	builder.WriteString(", ")
	builder.WriteString("affected_goats=")
	builder.WriteString(_m.AffectedGoats)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit=")
	builder.WriteString(_m.Unit)
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteString(", ")
	builder.WriteString("revenue=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revenue))
	builder.WriteString(", ")
	builder.WriteString("supplier_buyer=")
	builder.WriteString(_m.SupplierBuyer)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FarmOperations is a parsable slice of FarmOperation.
type FarmOperations []*FarmOperation
