// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/farmoperation"
)

// FarmOperationCreate is the builder for creating a FarmOperation entity.
type FarmOperationCreate struct {
	config
	mutation *FarmOperationMutation
	hooks    []Hook
}

// SetOperationDate sets the "operation_date" field.
func (_c *FarmOperationCreate) SetOperationDate(v time.Time) *FarmOperationCreate {
	_c.mutation.SetOperationDate(v)
	return _c
}

// SetNillableOperationDate sets the "operation_date" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableOperationDate(v *time.Time) *FarmOperationCreate {
	if v != nil {
		_c.SetOperationDate(*v)
	}
	return _c
}

// SetOperationType sets the "operation_type" field.
func (_c *FarmOperationCreate) SetOperationType(v farmoperation.OperationType) *FarmOperationCreate {
	_c.mutation.SetOperationType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FarmOperationCreate) SetDescription(v string) *FarmOperationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetPerformedBy sets the "performed_by" field.
func (_c *FarmOperationCreate) SetPerformedBy(v string) *FarmOperationCreate {
	_c.mutation.SetPerformedBy(v)
	return _c
}

// SetAffectedGoats sets the "affected_goats" field.
func (_c *FarmOperationCreate) SetAffectedGoats(v string) *FarmOperationCreate {
	_c.mutation.SetAffectedGoats(v)
	return _c
}

// SetNillableAffectedGoats sets the "affected_goats" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableAffectedGoats(v *string) *FarmOperationCreate {
	if v != nil {
		_c.SetAffectedGoats(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *FarmOperationCreate) SetQuantity(v float64) *FarmOperationCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableQuantity(v *float64) *FarmOperationCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *FarmOperationCreate) SetUnit(v string) *FarmOperationCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableUnit(v *string) *FarmOperationCreate {
	if v != nil {
		_c.SetUnit(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *FarmOperationCreate) SetCost(v float64) *FarmOperationCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableCost(v *float64) *FarmOperationCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetRevenue sets the "revenue" field.
func (_c *FarmOperationCreate) SetRevenue(v float64) *FarmOperationCreate {
	_c.mutation.SetRevenue(v)
	return _c
}

// SetNillableRevenue sets the "revenue" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableRevenue(v *float64) *FarmOperationCreate {
	if v != nil {
		_c.SetRevenue(*v)
	}
	return _c
}

// SetSupplierBuyer sets the "supplier_buyer" field.
func (_c *FarmOperationCreate) SetSupplierBuyer(v string) *FarmOperationCreate {
	_c.mutation.SetSupplierBuyer(v)
	return _c
}

// SetNillableSupplierBuyer sets the "supplier_buyer" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableSupplierBuyer(v *string) *FarmOperationCreate {
	if v != nil {
		_c.SetSupplierBuyer(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *FarmOperationCreate) SetNotes(v string) *FarmOperationCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableNotes(v *string) *FarmOperationCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FarmOperationCreate) SetCreatedAt(v time.Time) *FarmOperationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableCreatedAt(v *time.Time) *FarmOperationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FarmOperationCreate) SetUpdatedAt(v time.Time) *FarmOperationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FarmOperationCreate) SetNillableUpdatedAt(v *time.Time) *FarmOperationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the FarmOperationMutation object of the builder.
func (_c *FarmOperationCreate) Mutation() *FarmOperationMutation {
	return _c.mutation
}

// Save creates the FarmOperation in the database.
func (_c *FarmOperationCreate) Save(ctx context.Context) (*FarmOperation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FarmOperationCreate) SaveX(ctx context.Context) *FarmOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FarmOperationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FarmOperationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FarmOperationCreate) defaults() {
	if _, ok := _c.mutation.OperationDate(); !ok {
		v := farmoperation.DefaultOperationDate()
		_c.mutation.SetOperationDate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := farmoperation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := farmoperation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FarmOperationCreate) check() error {
	if _, ok := _c.mutation.OperationDate(); !ok {
		return &ValidationError{Name: "operation_date", err: errors.New(`ent: missing required field "FarmOperation.operation_date"`)}
	}
	if _, ok := _c.mutation.OperationType(); !ok {
		return &ValidationError{Name: "operation_type", err: errors.New(`ent: missing required field "FarmOperation.operation_type"`)}
	}
	if v, ok := _c.mutation.OperationType(); ok {
		if err := farmoperation.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "FarmOperation.operation_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "FarmOperation.description"`)}
	}
	if _, ok := _c.mutation.PerformedBy(); !ok {
		return &ValidationError{Name: "performed_by", err: errors.New(`ent: missing required field "FarmOperation.performed_by"`)}
	}
	if v, ok := _c.mutation.Cost(); ok {
		if err := farmoperation.CostValidator(v); err != nil {
			return &ValidationError{Name: "cost", err: fmt.Errorf(`ent: validator failed for field "FarmOperation.cost": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Revenue(); ok {
		if err := farmoperation.RevenueValidator(v); err != nil {
			return &ValidationError{Name: "revenue", err: fmt.Errorf(`ent: validator failed for field "FarmOperation.revenue": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FarmOperation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FarmOperation.updated_at"`)}
	}
	return nil
}

func (_c *FarmOperationCreate) sqlSave(ctx context.Context) (*FarmOperation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FarmOperationCreate) createSpec() (*FarmOperation, *sqlgraph.CreateSpec) {
	var (
		_node = &FarmOperation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(farmoperation.Table, sqlgraph.NewFieldSpec(farmoperation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OperationDate(); ok {
		_spec.SetField(farmoperation.FieldOperationDate, field.TypeTime, value)
		_node.OperationDate = value
	}
	if value, ok := _c.mutation.OperationType(); ok {
		_spec.SetField(farmoperation.FieldOperationType, field.TypeEnum, value)
		_node.OperationType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(farmoperation.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PerformedBy(); ok {
		_spec.SetField(farmoperation.FieldPerformedBy, field.TypeString, value)
		_node.PerformedBy = value
	}
	if value, ok := _c.mutation.AffectedGoats(); ok {
		_spec.SetField(farmoperation.FieldAffectedGoats, field.TypeString, value)
		_node.AffectedGoats = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(farmoperation.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(farmoperation.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(farmoperation.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Revenue(); ok {
		_spec.SetField(farmoperation.FieldRevenue, field.TypeFloat64, value)
		_node.Revenue = value
	}
	if value, ok := _c.mutation.SupplierBuyer(); ok {
		_spec.SetField(farmoperation.FieldSupplierBuyer, field.TypeString, value)
		_node.SupplierBuyer = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(farmoperation.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(farmoperation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(farmoperation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FarmOperationCreateBulk is the builder for creating many FarmOperation entities in bulk.
type FarmOperationCreateBulk struct {
	config
	err      error
	builders []*FarmOperationCreate
}

// Save creates the FarmOperation entities in the database.
func (_c *FarmOperationCreateBulk) Save(ctx context.Context) ([]*FarmOperation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FarmOperation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FarmOperationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FarmOperationCreateBulk) SaveX(ctx context.Context) []*FarmOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FarmOperationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FarmOperationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
