// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/breedingrecord"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/healthrecord"
	"github.com/farm/goat-manager/ent/milkrecord"
	"github.com/farm/goat-manager/ent/predicate"
)

// GoatQuery is the builder for querying Goat entities.
type GoatQuery struct {
	config
	ctx                 *QueryContext
	order               []goat.OrderOption
	inters              []Interceptor
	predicates          []predicate.Goat
	withMilkRecords     *MilkRecordQuery
	withHealthRecords   *HealthRecordQuery
	withBreedingRecords *BreedingRecordQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoatQuery builder.
func (_q *GoatQuery) Where(ps ...predicate.Goat) *GoatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GoatQuery) Limit(limit int) *GoatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GoatQuery) Offset(offset int) *GoatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GoatQuery) Unique(unique bool) *GoatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GoatQuery) Order(o ...goat.OrderOption) *GoatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMilkRecords chains the current query on the "milk_records" edge.
func (_q *GoatQuery) QueryMilkRecords() *MilkRecordQuery {
	query := (&MilkRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goat.Table, goat.FieldID, selector),
			sqlgraph.To(milkrecord.Table, milkrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goat.MilkRecordsTable, goat.MilkRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHealthRecords chains the current query on the "health_records" edge.
func (_q *GoatQuery) QueryHealthRecords() *HealthRecordQuery {
	query := (&HealthRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goat.Table, goat.FieldID, selector),
			sqlgraph.To(healthrecord.Table, healthrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goat.HealthRecordsTable, goat.HealthRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBreedingRecords chains the current query on the "breeding_records" edge.
func (_q *GoatQuery) QueryBreedingRecords() *BreedingRecordQuery {
	query := (&BreedingRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goat.Table, goat.FieldID, selector),
			sqlgraph.To(breedingrecord.Table, breedingrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goat.BreedingRecordsTable, goat.BreedingRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Goat entity from the query.
// Returns a *NotFoundError when no Goat was found.
func (_q *GoatQuery) First(ctx context.Context) (*Goat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GoatQuery) FirstX(ctx context.Context) *Goat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Goat ID from the query.
// Returns a *NotFoundError when no Goat ID was found.
func (_q *GoatQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GoatQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Goat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Goat entity is found.
// Returns a *NotFoundError when no Goat entities are found.
func (_q *GoatQuery) Only(ctx context.Context) (*Goat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goat.Label}
	default:
		return nil, &NotSingularError{goat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GoatQuery) OnlyX(ctx context.Context) *Goat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Goat ID in the query.
// Returns a *NotSingularError when more than one Goat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GoatQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goat.Label}
	default:
		err = &NotSingularError{goat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GoatQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Goats.
func (_q *GoatQuery) All(ctx context.Context) ([]*Goat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Goat, *GoatQuery]()
	return withInterceptors[[]*Goat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GoatQuery) AllX(ctx context.Context) []*Goat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Goat IDs.
func (_q *GoatQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(goat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GoatQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GoatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GoatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GoatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GoatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GoatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GoatQuery) Clone() *GoatQuery {
	if _q == nil {
		return nil
	}
	return &GoatQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]goat.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.Goat{}, _q.predicates...),
		withMilkRecords:     _q.withMilkRecords.Clone(),
		withHealthRecords:   _q.withHealthRecords.Clone(),
		withBreedingRecords: _q.withBreedingRecords.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMilkRecords tells the query-builder to eager-load the nodes that are connected to
// the "milk_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoatQuery) WithMilkRecords(opts ...func(*MilkRecordQuery)) *GoatQuery {
	query := (&MilkRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMilkRecords = query
	return _q
}

// WithHealthRecords tells the query-builder to eager-load the nodes that are connected to
// the "health_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoatQuery) WithHealthRecords(opts ...func(*HealthRecordQuery)) *GoatQuery {
	query := (&HealthRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHealthRecords = query
	return _q
}

// WithBreedingRecords tells the query-builder to eager-load the nodes that are connected to
// the "breeding_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoatQuery) WithBreedingRecords(opts ...func(*BreedingRecordQuery)) *GoatQuery {
	query := (&BreedingRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBreedingRecords = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Goat.Query().
//		GroupBy(goat.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GoatQuery) GroupBy(field string, fields ...string) *GoatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = goat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Goat.Query().
//		Select(goat.FieldName).
//		Scan(ctx, &v)
func (_q *GoatQuery) Select(fields ...string) *GoatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GoatSelect{GoatQuery: _q}
	sbuild.label = goat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoatSelect configured with the given aggregations.
func (_q *GoatQuery) Aggregate(fns ...AggregateFunc) *GoatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GoatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !goat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GoatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Goat, error) {
	var (
		nodes       = []*Goat{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withMilkRecords != nil,
			_q.withHealthRecords != nil,
			_q.withBreedingRecords != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Goat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Goat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMilkRecords; query != nil {
		if err := _q.loadMilkRecords(ctx, query, nodes,
			func(n *Goat) { n.Edges.MilkRecords = []*MilkRecord{} },
			func(n *Goat, e *MilkRecord) { n.Edges.MilkRecords = append(n.Edges.MilkRecords, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withHealthRecords; query != nil {
		if err := _q.loadHealthRecords(ctx, query, nodes,
			func(n *Goat) { n.Edges.HealthRecords = []*HealthRecord{} },
			func(n *Goat, e *HealthRecord) { n.Edges.HealthRecords = append(n.Edges.HealthRecords, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBreedingRecords; query != nil {
		if err := _q.loadBreedingRecords(ctx, query, nodes,
			func(n *Goat) { n.Edges.BreedingRecords = []*BreedingRecord{} },
			func(n *Goat, e *BreedingRecord) { n.Edges.BreedingRecords = append(n.Edges.BreedingRecords, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GoatQuery) loadMilkRecords(ctx context.Context, query *MilkRecordQuery, nodes []*Goat, init func(*Goat), assign func(*Goat, *MilkRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Goat)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(milkrecord.FieldGoatTag)
	}
	query.Where(predicate.MilkRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(goat.MilkRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GoatTag
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "goat_tag" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *GoatQuery) loadHealthRecords(ctx context.Context, query *HealthRecordQuery, nodes []*Goat, init func(*Goat), assign func(*Goat, *HealthRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Goat)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(healthrecord.FieldGoatTag)
	}
	query.Where(predicate.HealthRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(goat.HealthRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GoatTag
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "goat_tag" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *GoatQuery) loadBreedingRecords(ctx context.Context, query *BreedingRecordQuery, nodes []*Goat, init func(*Goat), assign func(*Goat, *BreedingRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Goat)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(breedingrecord.FieldDoeTag)
	}
	query.Where(predicate.BreedingRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(goat.BreedingRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DoeTag
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "doe_tag" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *GoatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GoatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(goat.Table, goat.Columns, sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goat.FieldID)
		for i := range fields {
			if fields[i] != goat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GoatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(goat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = goat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoatGroupBy is the group-by builder for Goat entities.
type GoatGroupBy struct {
	selector
	build *GoatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GoatGroupBy) Aggregate(fns ...AggregateFunc) *GoatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GoatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoatQuery, *GoatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GoatGroupBy) sqlScan(ctx context.Context, root *GoatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoatSelect is the builder for selecting fields of Goat entities.
type GoatSelect struct {
	*GoatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GoatSelect) Aggregate(fns ...AggregateFunc) *GoatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GoatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoatQuery, *GoatSelect](ctx, _s.GoatQuery, _s, _s.inters, v)
}

func (_s *GoatSelect) sqlScan(ctx context.Context, root *GoatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
