// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/healthrecord"
)

// HealthRecordCreate is the builder for creating a HealthRecord entity.
type HealthRecordCreate struct {
	config
	mutation *HealthRecordMutation
	hooks    []Hook
}

// SetGoatTag sets the "goat_tag" field.
func (_c *HealthRecordCreate) SetGoatTag(v string) *HealthRecordCreate {
	_c.mutation.SetGoatTag(v)
	return _c
}

// SetRecordDate sets the "record_date" field.
func (_c *HealthRecordCreate) SetRecordDate(v time.Time) *HealthRecordCreate {
	_c.mutation.SetRecordDate(v)
	return _c
}

// SetNillableRecordDate sets the "record_date" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableRecordDate(v *time.Time) *HealthRecordCreate {
	if v != nil {
		_c.SetRecordDate(*v)
	}
	return _c
}

// SetRecordType sets the "record_type" field.
func (_c *HealthRecordCreate) SetRecordType(v healthrecord.RecordType) *HealthRecordCreate {
	_c.mutation.SetRecordType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *HealthRecordCreate) SetDescription(v string) *HealthRecordCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetVeterinarian sets the "veterinarian" field.
func (_c *HealthRecordCreate) SetVeterinarian(v string) *HealthRecordCreate {
	_c.mutation.SetVeterinarian(v)
	return _c
}

// SetNillableVeterinarian sets the "veterinarian" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableVeterinarian(v *string) *HealthRecordCreate {
	if v != nil {
		_c.SetVeterinarian(*v)
	}
	return _c
}

// SetMedication sets the "medication" field.
func (_c *HealthRecordCreate) SetMedication(v string) *HealthRecordCreate {
	_c.mutation.SetMedication(v)
	return _c
}

// SetNillableMedication sets the "medication" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableMedication(v *string) *HealthRecordCreate {
	if v != nil {
		_c.SetMedication(*v)
	}
	return _c
}

// SetDosage sets the "dosage" field.
func (_c *HealthRecordCreate) SetDosage(v string) *HealthRecordCreate {
	_c.mutation.SetDosage(v)
	return _c
}

// SetNillableDosage sets the "dosage" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableDosage(v *string) *HealthRecordCreate {
	if v != nil {
		_c.SetDosage(*v)
	}
	return _c
}

// SetTemperature sets the "temperature" field.
func (_c *HealthRecordCreate) SetTemperature(v float64) *HealthRecordCreate {
	_c.mutation.SetTemperature(v)
	return _c
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableTemperature(v *float64) *HealthRecordCreate {
	if v != nil {
		_c.SetTemperature(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *HealthRecordCreate) SetWeight(v float64) *HealthRecordCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableWeight(v *float64) *HealthRecordCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetNextDueDate sets the "next_due_date" field.
func (_c *HealthRecordCreate) SetNextDueDate(v time.Time) *HealthRecordCreate {
	_c.mutation.SetNextDueDate(v)
	return _c
}

// SetNillableNextDueDate sets the "next_due_date" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableNextDueDate(v *time.Time) *HealthRecordCreate {
	if v != nil {
		_c.SetNextDueDate(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *HealthRecordCreate) SetCost(v float64) *HealthRecordCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableCost(v *float64) *HealthRecordCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *HealthRecordCreate) SetNotes(v string) *HealthRecordCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableNotes(v *string) *HealthRecordCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HealthRecordCreate) SetCreatedAt(v time.Time) *HealthRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableCreatedAt(v *time.Time) *HealthRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HealthRecordCreate) SetUpdatedAt(v time.Time) *HealthRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HealthRecordCreate) SetNillableUpdatedAt(v *time.Time) *HealthRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_c *HealthRecordCreate) SetGoatID(id string) *HealthRecordCreate {
	_c.mutation.SetGoatID(id)
	return _c
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_c *HealthRecordCreate) SetGoat(v *Goat) *HealthRecordCreate {
	return _c.SetGoatID(v.ID)
}

// Mutation returns the HealthRecordMutation object of the builder.
func (_c *HealthRecordCreate) Mutation() *HealthRecordMutation {
	return _c.mutation
}

// Save creates the HealthRecord in the database.
func (_c *HealthRecordCreate) Save(ctx context.Context) (*HealthRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HealthRecordCreate) SaveX(ctx context.Context) *HealthRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HealthRecordCreate) defaults() {
	if _, ok := _c.mutation.RecordDate(); !ok {
		v := healthrecord.DefaultRecordDate()
		_c.mutation.SetRecordDate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := healthrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := healthrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HealthRecordCreate) check() error {
	if _, ok := _c.mutation.GoatTag(); !ok {
		return &ValidationError{Name: "goat_tag", err: errors.New(`ent: missing required field "HealthRecord.goat_tag"`)}
	}
	if _, ok := _c.mutation.RecordDate(); !ok {
		return &ValidationError{Name: "record_date", err: errors.New(`ent: missing required field "HealthRecord.record_date"`)}
	}
	if _, ok := _c.mutation.RecordType(); !ok {
		return &ValidationError{Name: "record_type", err: errors.New(`ent: missing required field "HealthRecord.record_type"`)}
	}
	if v, ok := _c.mutation.RecordType(); ok {
		if err := healthrecord.RecordTypeValidator(v); err != nil {
			return &ValidationError{Name: "record_type", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.record_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "HealthRecord.description"`)}
	}
	if v, ok := _c.mutation.Weight(); ok {
		if err := healthrecord.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.weight": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Cost(); ok {
		if err := healthrecord.CostValidator(v); err != nil {
			return &ValidationError{Name: "cost", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.cost": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HealthRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HealthRecord.updated_at"`)}
	}
	if len(_c.mutation.GoatIDs()) == 0 {
		return &ValidationError{Name: "goat", err: errors.New(`ent: missing required edge "HealthRecord.goat"`)}
	}
	return nil
}

func (_c *HealthRecordCreate) sqlSave(ctx context.Context) (*HealthRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HealthRecordCreate) createSpec() (*HealthRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &HealthRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(healthrecord.Table, sqlgraph.NewFieldSpec(healthrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RecordDate(); ok {
		_spec.SetField(healthrecord.FieldRecordDate, field.TypeTime, value)
		_node.RecordDate = value
	}
	if value, ok := _c.mutation.RecordType(); ok {
		_spec.SetField(healthrecord.FieldRecordType, field.TypeEnum, value)
		_node.RecordType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(healthrecord.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Veterinarian(); ok {
		_spec.SetField(healthrecord.FieldVeterinarian, field.TypeString, value)
		_node.Veterinarian = value
	}
	if value, ok := _c.mutation.Medication(); ok {
		_spec.SetField(healthrecord.FieldMedication, field.TypeString, value)
		_node.Medication = value
	}
	if value, ok := _c.mutation.Dosage(); ok {
		_spec.SetField(healthrecord.FieldDosage, field.TypeString, value)
		_node.Dosage = value
	}
	if value, ok := _c.mutation.Temperature(); ok {
		_spec.SetField(healthrecord.FieldTemperature, field.TypeFloat64, value)
		_node.Temperature = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(healthrecord.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.NextDueDate(); ok {
		_spec.SetField(healthrecord.FieldNextDueDate, field.TypeTime, value)
		_node.NextDueDate = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(healthrecord.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(healthrecord.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(healthrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(healthrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthrecord.GoatTable,
			Columns: []string{healthrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GoatTag = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HealthRecordCreateBulk is the builder for creating many HealthRecord entities in bulk.
type HealthRecordCreateBulk struct {
	config
	err      error
	builders []*HealthRecordCreate
}

// Save creates the HealthRecord entities in the database.
func (_c *HealthRecordCreateBulk) Save(ctx context.Context) ([]*HealthRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HealthRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HealthRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HealthRecordCreateBulk) SaveX(ctx context.Context) []*HealthRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
