// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/healthrecord"
	"github.com/farm/goat-manager/ent/predicate"
)

// HealthRecordUpdate is the builder for updating HealthRecord entities.
type HealthRecordUpdate struct {
	config
	hooks    []Hook
	mutation *HealthRecordMutation
}

// Where appends a list predicates to the HealthRecordUpdate builder.
func (_u *HealthRecordUpdate) Where(ps ...predicate.HealthRecord) *HealthRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoatTag sets the "goat_tag" field.
func (_u *HealthRecordUpdate) SetGoatTag(v string) *HealthRecordUpdate {
	_u.mutation.SetGoatTag(v)
	return _u
}

// SetNillableGoatTag sets the "goat_tag" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableGoatTag(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetGoatTag(*v)
	}
	return _u
}

// SetRecordDate sets the "record_date" field.
func (_u *HealthRecordUpdate) SetRecordDate(v time.Time) *HealthRecordUpdate {
	_u.mutation.SetRecordDate(v)
	return _u
}

// SetNillableRecordDate sets the "record_date" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableRecordDate(v *time.Time) *HealthRecordUpdate {
	if v != nil {
		_u.SetRecordDate(*v)
	}
	return _u
}

// SetRecordType sets the "record_type" field.
func (_u *HealthRecordUpdate) SetRecordType(v healthrecord.RecordType) *HealthRecordUpdate {
	_u.mutation.SetRecordType(v)
	return _u
}

// SetNillableRecordType sets the "record_type" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableRecordType(v *healthrecord.RecordType) *HealthRecordUpdate {
	if v != nil {
		_u.SetRecordType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HealthRecordUpdate) SetDescription(v string) *HealthRecordUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableDescription(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVeterinarian sets the "veterinarian" field.
func (_u *HealthRecordUpdate) SetVeterinarian(v string) *HealthRecordUpdate {
	_u.mutation.SetVeterinarian(v)
	return _u
}

// SetNillableVeterinarian sets the "veterinarian" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableVeterinarian(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetVeterinarian(*v)
	}
	return _u
}

// ClearVeterinarian clears the value of the "veterinarian" field.
func (_u *HealthRecordUpdate) ClearVeterinarian() *HealthRecordUpdate {
	_u.mutation.ClearVeterinarian()
	return _u
}

// SetMedication sets the "medication" field.
func (_u *HealthRecordUpdate) SetMedication(v string) *HealthRecordUpdate {
	_u.mutation.SetMedication(v)
	return _u
}

// SetNillableMedication sets the "medication" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableMedication(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetMedication(*v)
	}
	return _u
}

// ClearMedication clears the value of the "medication" field.
func (_u *HealthRecordUpdate) ClearMedication() *HealthRecordUpdate {
	_u.mutation.ClearMedication()
	return _u
}

// SetDosage sets the "dosage" field.
func (_u *HealthRecordUpdate) SetDosage(v string) *HealthRecordUpdate {
	_u.mutation.SetDosage(v)
	return _u
}

// SetNillableDosage sets the "dosage" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableDosage(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetDosage(*v)
	}
	return _u
}

// ClearDosage clears the value of the "dosage" field.
func (_u *HealthRecordUpdate) ClearDosage() *HealthRecordUpdate {
	_u.mutation.ClearDosage()
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *HealthRecordUpdate) SetTemperature(v float64) *HealthRecordUpdate {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableTemperature(v *float64) *HealthRecordUpdate {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *HealthRecordUpdate) AddTemperature(v float64) *HealthRecordUpdate {
	_u.mutation.AddTemperature(v)
	return _u
}

// ClearTemperature clears the value of the "temperature" field.
func (_u *HealthRecordUpdate) ClearTemperature() *HealthRecordUpdate {
	_u.mutation.ClearTemperature()
	return _u
}

// SetWeight sets the "weight" field.
func (_u *HealthRecordUpdate) SetWeight(v float64) *HealthRecordUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableWeight(v *float64) *HealthRecordUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *HealthRecordUpdate) AddWeight(v float64) *HealthRecordUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// ClearWeight clears the value of the "weight" field.
func (_u *HealthRecordUpdate) ClearWeight() *HealthRecordUpdate {
	_u.mutation.ClearWeight()
	return _u
}

// SetNextDueDate sets the "next_due_date" field.
func (_u *HealthRecordUpdate) SetNextDueDate(v time.Time) *HealthRecordUpdate {
	_u.mutation.SetNextDueDate(v)
	return _u
}

// SetNillableNextDueDate sets the "next_due_date" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableNextDueDate(v *time.Time) *HealthRecordUpdate {
	if v != nil {
		_u.SetNextDueDate(*v)
	}
	return _u
}

// ClearNextDueDate clears the value of the "next_due_date" field.
func (_u *HealthRecordUpdate) ClearNextDueDate() *HealthRecordUpdate {
	_u.mutation.ClearNextDueDate()
	return _u
}

// SetCost sets the "cost" field.
func (_u *HealthRecordUpdate) SetCost(v float64) *HealthRecordUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableCost(v *float64) *HealthRecordUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *HealthRecordUpdate) AddCost(v float64) *HealthRecordUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// ClearCost clears the value of the "cost" field.
func (_u *HealthRecordUpdate) ClearCost() *HealthRecordUpdate {
	_u.mutation.ClearCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *HealthRecordUpdate) SetNotes(v string) *HealthRecordUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *HealthRecordUpdate) SetNillableNotes(v *string) *HealthRecordUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *HealthRecordUpdate) ClearNotes() *HealthRecordUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HealthRecordUpdate) SetUpdatedAt(v time.Time) *HealthRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_u *HealthRecordUpdate) SetGoatID(id string) *HealthRecordUpdate {
	_u.mutation.SetGoatID(id)
	return _u
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_u *HealthRecordUpdate) SetGoat(v *Goat) *HealthRecordUpdate {
	return _u.SetGoatID(v.ID)
}

// Mutation returns the HealthRecordMutation object of the builder.
func (_u *HealthRecordUpdate) Mutation() *HealthRecordMutation {
	return _u.mutation
}

// ClearGoat clears the "goat" edge to the Goat entity.
func (_u *HealthRecordUpdate) ClearGoat() *HealthRecordUpdate {
	_u.mutation.ClearGoat()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HealthRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HealthRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HealthRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := healthrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthRecordUpdate) check() error {
	if v, ok := _u.mutation.RecordType(); ok {
		if err := healthrecord.RecordTypeValidator(v); err != nil {
			return &ValidationError{Name: "record_type", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.record_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := healthrecord.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cost(); ok {
		if err := healthrecord.CostValidator(v); err != nil {
			return &ValidationError{Name: "cost", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.cost": %w`, err)}
		}
	}
	if _u.mutation.GoatCleared() && len(_u.mutation.GoatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HealthRecord.goat"`)
	}
	return nil
}

func (_u *HealthRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthrecord.Table, healthrecord.Columns, sqlgraph.NewFieldSpec(healthrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RecordDate(); ok {
		_spec.SetField(healthrecord.FieldRecordDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordType(); ok {
		_spec.SetField(healthrecord.FieldRecordType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(healthrecord.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Veterinarian(); ok {
		_spec.SetField(healthrecord.FieldVeterinarian, field.TypeString, value)
	}
	if _u.mutation.VeterinarianCleared() {
		_spec.ClearField(healthrecord.FieldVeterinarian, field.TypeString)
	}
	if value, ok := _u.mutation.Medication(); ok {
		_spec.SetField(healthrecord.FieldMedication, field.TypeString, value)
	}
	if _u.mutation.MedicationCleared() {
		_spec.ClearField(healthrecord.FieldMedication, field.TypeString)
	}
	if value, ok := _u.mutation.Dosage(); ok {
		_spec.SetField(healthrecord.FieldDosage, field.TypeString, value)
	}
	if _u.mutation.DosageCleared() {
		_spec.ClearField(healthrecord.FieldDosage, field.TypeString)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(healthrecord.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(healthrecord.FieldTemperature, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureCleared() {
		_spec.ClearField(healthrecord.FieldTemperature, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(healthrecord.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(healthrecord.FieldWeight, field.TypeFloat64, value)
	}
	if _u.mutation.WeightCleared() {
		_spec.ClearField(healthrecord.FieldWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.NextDueDate(); ok {
		_spec.SetField(healthrecord.FieldNextDueDate, field.TypeTime, value)
	}
	if _u.mutation.NextDueDateCleared() {
		_spec.ClearField(healthrecord.FieldNextDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(healthrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(healthrecord.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.CostCleared() {
		_spec.ClearField(healthrecord.FieldCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(healthrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(healthrecord.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(healthrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GoatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthrecord.GoatTable,
			Columns: []string{healthrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthrecord.GoatTable,
			Columns: []string{healthrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HealthRecordUpdateOne is the builder for updating a single HealthRecord entity.
type HealthRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HealthRecordMutation
}

// SetGoatTag sets the "goat_tag" field.
func (_u *HealthRecordUpdateOne) SetGoatTag(v string) *HealthRecordUpdateOne {
	_u.mutation.SetGoatTag(v)
	return _u
}

// SetNillableGoatTag sets the "goat_tag" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableGoatTag(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetGoatTag(*v)
	}
	return _u
}

// SetRecordDate sets the "record_date" field.
func (_u *HealthRecordUpdateOne) SetRecordDate(v time.Time) *HealthRecordUpdateOne {
	_u.mutation.SetRecordDate(v)
	return _u
}

// SetNillableRecordDate sets the "record_date" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableRecordDate(v *time.Time) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetRecordDate(*v)
	}
	return _u
}

// SetRecordType sets the "record_type" field.
func (_u *HealthRecordUpdateOne) SetRecordType(v healthrecord.RecordType) *HealthRecordUpdateOne {
	_u.mutation.SetRecordType(v)
	return _u
}

// SetNillableRecordType sets the "record_type" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableRecordType(v *healthrecord.RecordType) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetRecordType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HealthRecordUpdateOne) SetDescription(v string) *HealthRecordUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableDescription(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVeterinarian sets the "veterinarian" field.
func (_u *HealthRecordUpdateOne) SetVeterinarian(v string) *HealthRecordUpdateOne {
	_u.mutation.SetVeterinarian(v)
	return _u
}

// SetNillableVeterinarian sets the "veterinarian" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableVeterinarian(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetVeterinarian(*v)
	}
	return _u
}

// ClearVeterinarian clears the value of the "veterinarian" field.
func (_u *HealthRecordUpdateOne) ClearVeterinarian() *HealthRecordUpdateOne {
	_u.mutation.ClearVeterinarian()
	return _u
}

// SetMedication sets the "medication" field.
func (_u *HealthRecordUpdateOne) SetMedication(v string) *HealthRecordUpdateOne {
	_u.mutation.SetMedication(v)
	return _u
}

// SetNillableMedication sets the "medication" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableMedication(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetMedication(*v)
	}
	return _u
}

// ClearMedication clears the value of the "medication" field.
func (_u *HealthRecordUpdateOne) ClearMedication() *HealthRecordUpdateOne {
	_u.mutation.ClearMedication()
	return _u
}

// SetDosage sets the "dosage" field.
func (_u *HealthRecordUpdateOne) SetDosage(v string) *HealthRecordUpdateOne {
	_u.mutation.SetDosage(v)
	return _u
}

// SetNillableDosage sets the "dosage" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableDosage(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetDosage(*v)
	}
	return _u
}

// ClearDosage clears the value of the "dosage" field.
func (_u *HealthRecordUpdateOne) ClearDosage() *HealthRecordUpdateOne {
	_u.mutation.ClearDosage()
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *HealthRecordUpdateOne) SetTemperature(v float64) *HealthRecordUpdateOne {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableTemperature(v *float64) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *HealthRecordUpdateOne) AddTemperature(v float64) *HealthRecordUpdateOne {
	_u.mutation.AddTemperature(v)
	return _u
}

// ClearTemperature clears the value of the "temperature" field.
func (_u *HealthRecordUpdateOne) ClearTemperature() *HealthRecordUpdateOne {
	_u.mutation.ClearTemperature()
	return _u
}

// SetWeight sets the "weight" field.
func (_u *HealthRecordUpdateOne) SetWeight(v float64) *HealthRecordUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableWeight(v *float64) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *HealthRecordUpdateOne) AddWeight(v float64) *HealthRecordUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// ClearWeight clears the value of the "weight" field.
func (_u *HealthRecordUpdateOne) ClearWeight() *HealthRecordUpdateOne {
	_u.mutation.ClearWeight()
	return _u
}

// SetNextDueDate sets the "next_due_date" field.
func (_u *HealthRecordUpdateOne) SetNextDueDate(v time.Time) *HealthRecordUpdateOne {
	_u.mutation.SetNextDueDate(v)
	return _u
}

// SetNillableNextDueDate sets the "next_due_date" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableNextDueDate(v *time.Time) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetNextDueDate(*v)
	}
	return _u
}

// ClearNextDueDate clears the value of the "next_due_date" field.
func (_u *HealthRecordUpdateOne) ClearNextDueDate() *HealthRecordUpdateOne {
	_u.mutation.ClearNextDueDate()
	return _u
}

// SetCost sets the "cost" field.
func (_u *HealthRecordUpdateOne) SetCost(v float64) *HealthRecordUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableCost(v *float64) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *HealthRecordUpdateOne) AddCost(v float64) *HealthRecordUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// ClearCost clears the value of the "cost" field.
func (_u *HealthRecordUpdateOne) ClearCost() *HealthRecordUpdateOne {
	_u.mutation.ClearCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *HealthRecordUpdateOne) SetNotes(v string) *HealthRecordUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *HealthRecordUpdateOne) SetNillableNotes(v *string) *HealthRecordUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *HealthRecordUpdateOne) ClearNotes() *HealthRecordUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HealthRecordUpdateOne) SetUpdatedAt(v time.Time) *HealthRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_u *HealthRecordUpdateOne) SetGoatID(id string) *HealthRecordUpdateOne {
	_u.mutation.SetGoatID(id)
	return _u
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_u *HealthRecordUpdateOne) SetGoat(v *Goat) *HealthRecordUpdateOne {
	return _u.SetGoatID(v.ID)
}

// Mutation returns the HealthRecordMutation object of the builder.
func (_u *HealthRecordUpdateOne) Mutation() *HealthRecordMutation {
	return _u.mutation
}

// ClearGoat clears the "goat" edge to the Goat entity.
func (_u *HealthRecordUpdateOne) ClearGoat() *HealthRecordUpdateOne {
	_u.mutation.ClearGoat()
	return _u
}

// Where appends a list predicates to the HealthRecordUpdate builder.
func (_u *HealthRecordUpdateOne) Where(ps ...predicate.HealthRecord) *HealthRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HealthRecordUpdateOne) Select(field string, fields ...string) *HealthRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HealthRecord entity.
func (_u *HealthRecordUpdateOne) Save(ctx context.Context) (*HealthRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthRecordUpdateOne) SaveX(ctx context.Context) *HealthRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HealthRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HealthRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := healthrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthRecordUpdateOne) check() error {
	if v, ok := _u.mutation.RecordType(); ok {
		if err := healthrecord.RecordTypeValidator(v); err != nil {
			return &ValidationError{Name: "record_type", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.record_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := healthrecord.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cost(); ok {
		if err := healthrecord.CostValidator(v); err != nil {
			return &ValidationError{Name: "cost", err: fmt.Errorf(`ent: validator failed for field "HealthRecord.cost": %w`, err)}
		}
	}
	if _u.mutation.GoatCleared() && len(_u.mutation.GoatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HealthRecord.goat"`)
	}
	return nil
}

func (_u *HealthRecordUpdateOne) sqlSave(ctx context.Context) (_node *HealthRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthrecord.Table, healthrecord.Columns, sqlgraph.NewFieldSpec(healthrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HealthRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, healthrecord.FieldID)
		for _, f := range fields {
			if !healthrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != healthrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RecordDate(); ok {
		_spec.SetField(healthrecord.FieldRecordDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordType(); ok {
		_spec.SetField(healthrecord.FieldRecordType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(healthrecord.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Veterinarian(); ok {
		_spec.SetField(healthrecord.FieldVeterinarian, field.TypeString, value)
	}
	if _u.mutation.VeterinarianCleared() {
		_spec.ClearField(healthrecord.FieldVeterinarian, field.TypeString)
	}
	if value, ok := _u.mutation.Medication(); ok {
		_spec.SetField(healthrecord.FieldMedication, field.TypeString, value)
	}
	if _u.mutation.MedicationCleared() {
		_spec.ClearField(healthrecord.FieldMedication, field.TypeString)
	}
	if value, ok := _u.mutation.Dosage(); ok {
		_spec.SetField(healthrecord.FieldDosage, field.TypeString, value)
	}
	if _u.mutation.DosageCleared() {
		_spec.ClearField(healthrecord.FieldDosage, field.TypeString)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(healthrecord.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(healthrecord.FieldTemperature, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureCleared() {
		_spec.ClearField(healthrecord.FieldTemperature, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(healthrecord.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(healthrecord.FieldWeight, field.TypeFloat64, value)
	}
	if _u.mutation.WeightCleared() {
		_spec.ClearField(healthrecord.FieldWeight, field.TypeFloat64)
	}
	if value, ok := _u.mutation.NextDueDate(); ok {
		_spec.SetField(healthrecord.FieldNextDueDate, field.TypeTime, value)
	}
	if _u.mutation.NextDueDateCleared() {
		_spec.ClearField(healthrecord.FieldNextDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(healthrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(healthrecord.FieldCost, field.TypeFloat64, value)
	}
	if _u.mutation.CostCleared() {
		_spec.ClearField(healthrecord.FieldCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(healthrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(healthrecord.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(healthrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GoatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthrecord.GoatTable,
			Columns: []string{healthrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthrecord.GoatTable,
			Columns: []string{healthrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HealthRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
