// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/milkrecord"
)

// MilkRecordCreate is the builder for creating a MilkRecord entity.
type MilkRecordCreate struct {
	config
	mutation *MilkRecordMutation
	hooks    []Hook
}

// SetGoatTag sets the "goat_tag" field.
func (_c *MilkRecordCreate) SetGoatTag(v string) *MilkRecordCreate {
	_c.mutation.SetGoatTag(v)
	return _c
}

// SetMilkingTime sets the "milking_time" field.
func (_c *MilkRecordCreate) SetMilkingTime(v time.Time) *MilkRecordCreate {
	_c.mutation.SetMilkingTime(v)
	return _c
}

// SetMilkingSession sets the "milking_session" field.
func (_c *MilkRecordCreate) SetMilkingSession(v milkrecord.MilkingSession) *MilkRecordCreate {
	_c.mutation.SetMilkingSession(v)
	return _c
}

// SetVolumeLiters sets the "volume_liters" field.
func (_c *MilkRecordCreate) SetVolumeLiters(v float64) *MilkRecordCreate {
	_c.mutation.SetVolumeLiters(v)
	return _c
}

// SetFatContent sets the "fat_content" field.
func (_c *MilkRecordCreate) SetFatContent(v float64) *MilkRecordCreate {
	_c.mutation.SetFatContent(v)
	return _c
}

// SetNillableFatContent sets the "fat_content" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableFatContent(v *float64) *MilkRecordCreate {
	if v != nil {
		_c.SetFatContent(*v)
	}
	return _c
}

// SetProteinContent sets the "protein_content" field.
func (_c *MilkRecordCreate) SetProteinContent(v float64) *MilkRecordCreate {
	_c.mutation.SetProteinContent(v)
	return _c
}

// SetNillableProteinContent sets the "protein_content" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableProteinContent(v *float64) *MilkRecordCreate {
	if v != nil {
		_c.SetProteinContent(*v)
	}
	return _c
}

// SetSomaticCellCount sets the "somatic_cell_count" field.
func (_c *MilkRecordCreate) SetSomaticCellCount(v float64) *MilkRecordCreate {
	_c.mutation.SetSomaticCellCount(v)
	return _c
}

// SetNillableSomaticCellCount sets the "somatic_cell_count" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableSomaticCellCount(v *float64) *MilkRecordCreate {
	if v != nil {
		_c.SetSomaticCellCount(*v)
	}
	return _c
}

// SetQualityGrade sets the "quality_grade" field.
func (_c *MilkRecordCreate) SetQualityGrade(v milkrecord.QualityGrade) *MilkRecordCreate {
	_c.mutation.SetQualityGrade(v)
	return _c
}

// SetNillableQualityGrade sets the "quality_grade" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableQualityGrade(v *milkrecord.QualityGrade) *MilkRecordCreate {
	if v != nil {
		_c.SetQualityGrade(*v)
	}
	return _c
}

// SetMilkedBy sets the "milked_by" field.
func (_c *MilkRecordCreate) SetMilkedBy(v string) *MilkRecordCreate {
	_c.mutation.SetMilkedBy(v)
	return _c
}

// SetNillableMilkedBy sets the "milked_by" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableMilkedBy(v *string) *MilkRecordCreate {
	if v != nil {
		_c.SetMilkedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *MilkRecordCreate) SetNotes(v string) *MilkRecordCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableNotes(v *string) *MilkRecordCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MilkRecordCreate) SetCreatedAt(v time.Time) *MilkRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MilkRecordCreate) SetNillableCreatedAt(v *time.Time) *MilkRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_c *MilkRecordCreate) SetGoatID(id string) *MilkRecordCreate {
	_c.mutation.SetGoatID(id)
	return _c
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_c *MilkRecordCreate) SetGoat(v *Goat) *MilkRecordCreate {
	return _c.SetGoatID(v.ID)
}

// Mutation returns the MilkRecordMutation object of the builder.
func (_c *MilkRecordCreate) Mutation() *MilkRecordMutation {
	return _c.mutation
}

// Save creates the MilkRecord in the database.
func (_c *MilkRecordCreate) Save(ctx context.Context) (*MilkRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MilkRecordCreate) SaveX(ctx context.Context) *MilkRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilkRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilkRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MilkRecordCreate) defaults() {
	if _, ok := _c.mutation.QualityGrade(); !ok {
		v := milkrecord.DefaultQualityGrade
		_c.mutation.SetQualityGrade(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := milkrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MilkRecordCreate) check() error {
	if _, ok := _c.mutation.GoatTag(); !ok {
		return &ValidationError{Name: "goat_tag", err: errors.New(`ent: missing required field "MilkRecord.goat_tag"`)}
	}
	if _, ok := _c.mutation.MilkingTime(); !ok {
		return &ValidationError{Name: "milking_time", err: errors.New(`ent: missing required field "MilkRecord.milking_time"`)}
	}
	if _, ok := _c.mutation.MilkingSession(); !ok {
		return &ValidationError{Name: "milking_session", err: errors.New(`ent: missing required field "MilkRecord.milking_session"`)}
	}
	if v, ok := _c.mutation.MilkingSession(); ok {
		if err := milkrecord.MilkingSessionValidator(v); err != nil {
			return &ValidationError{Name: "milking_session", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.milking_session": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VolumeLiters(); !ok {
		return &ValidationError{Name: "volume_liters", err: errors.New(`ent: missing required field "MilkRecord.volume_liters"`)}
	}
	if v, ok := _c.mutation.VolumeLiters(); ok {
		if err := milkrecord.VolumeLitersValidator(v); err != nil {
			return &ValidationError{Name: "volume_liters", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.volume_liters": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FatContent(); ok {
		if err := milkrecord.FatContentValidator(v); err != nil {
			return &ValidationError{Name: "fat_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.fat_content": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProteinContent(); ok {
		if err := milkrecord.ProteinContentValidator(v); err != nil {
			return &ValidationError{Name: "protein_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.protein_content": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SomaticCellCount(); ok {
		if err := milkrecord.SomaticCellCountValidator(v); err != nil {
			return &ValidationError{Name: "somatic_cell_count", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.somatic_cell_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QualityGrade(); !ok {
		return &ValidationError{Name: "quality_grade", err: errors.New(`ent: missing required field "MilkRecord.quality_grade"`)}
	}
	if v, ok := _c.mutation.QualityGrade(); ok {
		if err := milkrecord.QualityGradeValidator(v); err != nil {
			return &ValidationError{Name: "quality_grade", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.quality_grade": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MilkRecord.created_at"`)}
	}
	if len(_c.mutation.GoatIDs()) == 0 {
		return &ValidationError{Name: "goat", err: errors.New(`ent: missing required edge "MilkRecord.goat"`)}
	}
	return nil
}

func (_c *MilkRecordCreate) sqlSave(ctx context.Context) (*MilkRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MilkRecordCreate) createSpec() (*MilkRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &MilkRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(milkrecord.Table, sqlgraph.NewFieldSpec(milkrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MilkingTime(); ok {
		_spec.SetField(milkrecord.FieldMilkingTime, field.TypeTime, value)
		_node.MilkingTime = value
	}
	if value, ok := _c.mutation.MilkingSession(); ok {
		_spec.SetField(milkrecord.FieldMilkingSession, field.TypeEnum, value)
		_node.MilkingSession = value
	}
	if value, ok := _c.mutation.VolumeLiters(); ok {
		_spec.SetField(milkrecord.FieldVolumeLiters, field.TypeFloat64, value)
		_node.VolumeLiters = value
	}
	if value, ok := _c.mutation.FatContent(); ok {
		_spec.SetField(milkrecord.FieldFatContent, field.TypeFloat64, value)
		_node.FatContent = value
	}
	if value, ok := _c.mutation.ProteinContent(); ok {
		_spec.SetField(milkrecord.FieldProteinContent, field.TypeFloat64, value)
		_node.ProteinContent = value
	}
	if value, ok := _c.mutation.SomaticCellCount(); ok {
		_spec.SetField(milkrecord.FieldSomaticCellCount, field.TypeFloat64, value)
		_node.SomaticCellCount = value
	}
	if value, ok := _c.mutation.QualityGrade(); ok {
		_spec.SetField(milkrecord.FieldQualityGrade, field.TypeEnum, value)
		_node.QualityGrade = value
	}
	if value, ok := _c.mutation.MilkedBy(); ok {
		_spec.SetField(milkrecord.FieldMilkedBy, field.TypeString, value)
		_node.MilkedBy = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(milkrecord.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(milkrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milkrecord.GoatTable,
			Columns: []string{milkrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GoatTag = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MilkRecordCreateBulk is the builder for creating many MilkRecord entities in bulk.
type MilkRecordCreateBulk struct {
	config
	err      error
	builders []*MilkRecordCreate
}

// Save creates the MilkRecord entities in the database.
func (_c *MilkRecordCreateBulk) Save(ctx context.Context) ([]*MilkRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MilkRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MilkRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MilkRecordCreateBulk) SaveX(ctx context.Context) []*MilkRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilkRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilkRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
