// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/milkrecord"
	"github.com/farm/goat-manager/ent/predicate"
)

// MilkRecordUpdate is the builder for updating MilkRecord entities.
type MilkRecordUpdate struct {
	config
	hooks    []Hook
	mutation *MilkRecordMutation
}

// Where appends a list predicates to the MilkRecordUpdate builder.
func (_u *MilkRecordUpdate) Where(ps ...predicate.MilkRecord) *MilkRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoatTag sets the "goat_tag" field.
func (_u *MilkRecordUpdate) SetGoatTag(v string) *MilkRecordUpdate {
	_u.mutation.SetGoatTag(v)
	return _u
}

// SetNillableGoatTag sets the "goat_tag" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableGoatTag(v *string) *MilkRecordUpdate {
	if v != nil {
		_u.SetGoatTag(*v)
	}
	return _u
}

// SetMilkingTime sets the "milking_time" field.
func (_u *MilkRecordUpdate) SetMilkingTime(v time.Time) *MilkRecordUpdate {
	_u.mutation.SetMilkingTime(v)
	return _u
}

// SetNillableMilkingTime sets the "milking_time" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableMilkingTime(v *time.Time) *MilkRecordUpdate {
	if v != nil {
		_u.SetMilkingTime(*v)
	}
	return _u
}

// SetMilkingSession sets the "milking_session" field.
func (_u *MilkRecordUpdate) SetMilkingSession(v milkrecord.MilkingSession) *MilkRecordUpdate {
	_u.mutation.SetMilkingSession(v)
	return _u
}

// SetNillableMilkingSession sets the "milking_session" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableMilkingSession(v *milkrecord.MilkingSession) *MilkRecordUpdate {
	if v != nil {
		_u.SetMilkingSession(*v)
	}
	return _u
}

// SetVolumeLiters sets the "volume_liters" field.
func (_u *MilkRecordUpdate) SetVolumeLiters(v float64) *MilkRecordUpdate {
	_u.mutation.ResetVolumeLiters()
	_u.mutation.SetVolumeLiters(v)
	return _u
}

// SetNillableVolumeLiters sets the "volume_liters" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableVolumeLiters(v *float64) *MilkRecordUpdate {
	if v != nil {
		_u.SetVolumeLiters(*v)
	}
	return _u
}

// AddVolumeLiters adds value to the "volume_liters" field.
func (_u *MilkRecordUpdate) AddVolumeLiters(v float64) *MilkRecordUpdate {
	_u.mutation.AddVolumeLiters(v)
	return _u
}

// SetFatContent sets the "fat_content" field.
func (_u *MilkRecordUpdate) SetFatContent(v float64) *MilkRecordUpdate {
	_u.mutation.ResetFatContent()
	_u.mutation.SetFatContent(v)
	return _u
}

// SetNillableFatContent sets the "fat_content" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableFatContent(v *float64) *MilkRecordUpdate {
	if v != nil {
		_u.SetFatContent(*v)
	}
	return _u
}

// AddFatContent adds value to the "fat_content" field.
func (_u *MilkRecordUpdate) AddFatContent(v float64) *MilkRecordUpdate {
	_u.mutation.AddFatContent(v)
	return _u
}

// ClearFatContent clears the value of the "fat_content" field.
func (_u *MilkRecordUpdate) ClearFatContent() *MilkRecordUpdate {
	_u.mutation.ClearFatContent()
	return _u
}

// SetProteinContent sets the "protein_content" field.
func (_u *MilkRecordUpdate) SetProteinContent(v float64) *MilkRecordUpdate {
	_u.mutation.ResetProteinContent()
	_u.mutation.SetProteinContent(v)
	return _u
}

// SetNillableProteinContent sets the "protein_content" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableProteinContent(v *float64) *MilkRecordUpdate {
	if v != nil {
		_u.SetProteinContent(*v)
	}
	return _u
}

// AddProteinContent adds value to the "protein_content" field.
func (_u *MilkRecordUpdate) AddProteinContent(v float64) *MilkRecordUpdate {
	_u.mutation.AddProteinContent(v)
	return _u
}

// ClearProteinContent clears the value of the "protein_content" field.
func (_u *MilkRecordUpdate) ClearProteinContent() *MilkRecordUpdate {
	_u.mutation.ClearProteinContent()
	return _u
}

// SetSomaticCellCount sets the "somatic_cell_count" field.
func (_u *MilkRecordUpdate) SetSomaticCellCount(v float64) *MilkRecordUpdate {
	_u.mutation.ResetSomaticCellCount()
	_u.mutation.SetSomaticCellCount(v)
	return _u
}

// SetNillableSomaticCellCount sets the "somatic_cell_count" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableSomaticCellCount(v *float64) *MilkRecordUpdate {
	if v != nil {
		_u.SetSomaticCellCount(*v)
	}
	return _u
}

// AddSomaticCellCount adds value to the "somatic_cell_count" field.
func (_u *MilkRecordUpdate) AddSomaticCellCount(v float64) *MilkRecordUpdate {
	_u.mutation.AddSomaticCellCount(v)
	return _u
}

// ClearSomaticCellCount clears the value of the "somatic_cell_count" field.
func (_u *MilkRecordUpdate) ClearSomaticCellCount() *MilkRecordUpdate {
	_u.mutation.ClearSomaticCellCount()
	return _u
}

// SetQualityGrade sets the "quality_grade" field.
func (_u *MilkRecordUpdate) SetQualityGrade(v milkrecord.QualityGrade) *MilkRecordUpdate {
	_u.mutation.SetQualityGrade(v)
	return _u
}

// SetNillableQualityGrade sets the "quality_grade" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableQualityGrade(v *milkrecord.QualityGrade) *MilkRecordUpdate {
	if v != nil {
		_u.SetQualityGrade(*v)
	}
	return _u
}

// SetMilkedBy sets the "milked_by" field.
func (_u *MilkRecordUpdate) SetMilkedBy(v string) *MilkRecordUpdate {
	_u.mutation.SetMilkedBy(v)
	return _u
}

// SetNillableMilkedBy sets the "milked_by" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableMilkedBy(v *string) *MilkRecordUpdate {
	if v != nil {
		_u.SetMilkedBy(*v)
	}
	return _u
}

// ClearMilkedBy clears the value of the "milked_by" field.
func (_u *MilkRecordUpdate) ClearMilkedBy() *MilkRecordUpdate {
	_u.mutation.ClearMilkedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MilkRecordUpdate) SetNotes(v string) *MilkRecordUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MilkRecordUpdate) SetNillableNotes(v *string) *MilkRecordUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MilkRecordUpdate) ClearNotes() *MilkRecordUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_u *MilkRecordUpdate) SetGoatID(id string) *MilkRecordUpdate {
	_u.mutation.SetGoatID(id)
	return _u
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_u *MilkRecordUpdate) SetGoat(v *Goat) *MilkRecordUpdate {
	return _u.SetGoatID(v.ID)
}

// Mutation returns the MilkRecordMutation object of the builder.
func (_u *MilkRecordUpdate) Mutation() *MilkRecordMutation {
	return _u.mutation
}

// ClearGoat clears the "goat" edge to the Goat entity.
func (_u *MilkRecordUpdate) ClearGoat() *MilkRecordUpdate {
	_u.mutation.ClearGoat()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MilkRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MilkRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MilkRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MilkRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MilkRecordUpdate) check() error {
	if v, ok := _u.mutation.MilkingSession(); ok {
		if err := milkrecord.MilkingSessionValidator(v); err != nil {
			return &ValidationError{Name: "milking_session", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.milking_session": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VolumeLiters(); ok {
		if err := milkrecord.VolumeLitersValidator(v); err != nil {
			return &ValidationError{Name: "volume_liters", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.volume_liters": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FatContent(); ok {
		if err := milkrecord.FatContentValidator(v); err != nil {
			return &ValidationError{Name: "fat_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.fat_content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProteinContent(); ok {
		if err := milkrecord.ProteinContentValidator(v); err != nil {
			return &ValidationError{Name: "protein_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.protein_content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SomaticCellCount(); ok {
		if err := milkrecord.SomaticCellCountValidator(v); err != nil {
			return &ValidationError{Name: "somatic_cell_count", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.somatic_cell_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityGrade(); ok {
		if err := milkrecord.QualityGradeValidator(v); err != nil {
			return &ValidationError{Name: "quality_grade", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.quality_grade": %w`, err)}
		}
	}
	if _u.mutation.GoatCleared() && len(_u.mutation.GoatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MilkRecord.goat"`)
	}
	return nil
}

func (_u *MilkRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(milkrecord.Table, milkrecord.Columns, sqlgraph.NewFieldSpec(milkrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MilkingTime(); ok {
		_spec.SetField(milkrecord.FieldMilkingTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MilkingSession(); ok {
		_spec.SetField(milkrecord.FieldMilkingSession, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VolumeLiters(); ok {
		_spec.SetField(milkrecord.FieldVolumeLiters, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolumeLiters(); ok {
		_spec.AddField(milkrecord.FieldVolumeLiters, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FatContent(); ok {
		_spec.SetField(milkrecord.FieldFatContent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFatContent(); ok {
		_spec.AddField(milkrecord.FieldFatContent, field.TypeFloat64, value)
	}
	if _u.mutation.FatContentCleared() {
		_spec.ClearField(milkrecord.FieldFatContent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProteinContent(); ok {
		_spec.SetField(milkrecord.FieldProteinContent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProteinContent(); ok {
		_spec.AddField(milkrecord.FieldProteinContent, field.TypeFloat64, value)
	}
	if _u.mutation.ProteinContentCleared() {
		_spec.ClearField(milkrecord.FieldProteinContent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SomaticCellCount(); ok {
		_spec.SetField(milkrecord.FieldSomaticCellCount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSomaticCellCount(); ok {
		_spec.AddField(milkrecord.FieldSomaticCellCount, field.TypeFloat64, value)
	}
	if _u.mutation.SomaticCellCountCleared() {
		_spec.ClearField(milkrecord.FieldSomaticCellCount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityGrade(); ok {
		_spec.SetField(milkrecord.FieldQualityGrade, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MilkedBy(); ok {
		_spec.SetField(milkrecord.FieldMilkedBy, field.TypeString, value)
	}
	if _u.mutation.MilkedByCleared() {
		_spec.ClearField(milkrecord.FieldMilkedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(milkrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(milkrecord.FieldNotes, field.TypeString)
	}
	if _u.mutation.GoatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milkrecord.GoatTable,
			Columns: []string{milkrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milkrecord.GoatTable,
			Columns: []string{milkrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{milkrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MilkRecordUpdateOne is the builder for updating a single MilkRecord entity.
type MilkRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MilkRecordMutation
}

// SetGoatTag sets the "goat_tag" field.
func (_u *MilkRecordUpdateOne) SetGoatTag(v string) *MilkRecordUpdateOne {
	_u.mutation.SetGoatTag(v)
	return _u
}

// SetNillableGoatTag sets the "goat_tag" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableGoatTag(v *string) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetGoatTag(*v)
	}
	return _u
}

// SetMilkingTime sets the "milking_time" field.
func (_u *MilkRecordUpdateOne) SetMilkingTime(v time.Time) *MilkRecordUpdateOne {
	_u.mutation.SetMilkingTime(v)
	return _u
}

// SetNillableMilkingTime sets the "milking_time" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableMilkingTime(v *time.Time) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetMilkingTime(*v)
	}
	return _u
}

// SetMilkingSession sets the "milking_session" field.
func (_u *MilkRecordUpdateOne) SetMilkingSession(v milkrecord.MilkingSession) *MilkRecordUpdateOne {
	_u.mutation.SetMilkingSession(v)
	return _u
}

// SetNillableMilkingSession sets the "milking_session" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableMilkingSession(v *milkrecord.MilkingSession) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetMilkingSession(*v)
	}
	return _u
}

// SetVolumeLiters sets the "volume_liters" field.
func (_u *MilkRecordUpdateOne) SetVolumeLiters(v float64) *MilkRecordUpdateOne {
	_u.mutation.ResetVolumeLiters()
	_u.mutation.SetVolumeLiters(v)
	return _u
}

// SetNillableVolumeLiters sets the "volume_liters" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableVolumeLiters(v *float64) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetVolumeLiters(*v)
	}
	return _u
}

// AddVolumeLiters adds value to the "volume_liters" field.
func (_u *MilkRecordUpdateOne) AddVolumeLiters(v float64) *MilkRecordUpdateOne {
	_u.mutation.AddVolumeLiters(v)
	return _u
}

// SetFatContent sets the "fat_content" field.
func (_u *MilkRecordUpdateOne) SetFatContent(v float64) *MilkRecordUpdateOne {
	_u.mutation.ResetFatContent()
	_u.mutation.SetFatContent(v)
	return _u
}

// SetNillableFatContent sets the "fat_content" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableFatContent(v *float64) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetFatContent(*v)
	}
	return _u
}

// AddFatContent adds value to the "fat_content" field.
func (_u *MilkRecordUpdateOne) AddFatContent(v float64) *MilkRecordUpdateOne {
	_u.mutation.AddFatContent(v)
	return _u
}

// ClearFatContent clears the value of the "fat_content" field.
func (_u *MilkRecordUpdateOne) ClearFatContent() *MilkRecordUpdateOne {
	_u.mutation.ClearFatContent()
	return _u
}

// SetProteinContent sets the "protein_content" field.
func (_u *MilkRecordUpdateOne) SetProteinContent(v float64) *MilkRecordUpdateOne {
	_u.mutation.ResetProteinContent()
	_u.mutation.SetProteinContent(v)
	return _u
}

// SetNillableProteinContent sets the "protein_content" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableProteinContent(v *float64) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetProteinContent(*v)
	}
	return _u
}

// AddProteinContent adds value to the "protein_content" field.
func (_u *MilkRecordUpdateOne) AddProteinContent(v float64) *MilkRecordUpdateOne {
	_u.mutation.AddProteinContent(v)
	return _u
}

// ClearProteinContent clears the value of the "protein_content" field.
func (_u *MilkRecordUpdateOne) ClearProteinContent() *MilkRecordUpdateOne {
	_u.mutation.ClearProteinContent()
	return _u
}

// SetSomaticCellCount sets the "somatic_cell_count" field.
func (_u *MilkRecordUpdateOne) SetSomaticCellCount(v float64) *MilkRecordUpdateOne {
	_u.mutation.ResetSomaticCellCount()
	_u.mutation.SetSomaticCellCount(v)
	return _u
}

// SetNillableSomaticCellCount sets the "somatic_cell_count" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableSomaticCellCount(v *float64) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetSomaticCellCount(*v)
	}
	return _u
}

// AddSomaticCellCount adds value to the "somatic_cell_count" field.
func (_u *MilkRecordUpdateOne) AddSomaticCellCount(v float64) *MilkRecordUpdateOne {
	_u.mutation.AddSomaticCellCount(v)
	return _u
}

// ClearSomaticCellCount clears the value of the "somatic_cell_count" field.
func (_u *MilkRecordUpdateOne) ClearSomaticCellCount() *MilkRecordUpdateOne {
	_u.mutation.ClearSomaticCellCount()
	return _u
}

// SetQualityGrade sets the "quality_grade" field.
func (_u *MilkRecordUpdateOne) SetQualityGrade(v milkrecord.QualityGrade) *MilkRecordUpdateOne {
	_u.mutation.SetQualityGrade(v)
	return _u
}

// SetNillableQualityGrade sets the "quality_grade" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableQualityGrade(v *milkrecord.QualityGrade) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetQualityGrade(*v)
	}
	return _u
}

// SetMilkedBy sets the "milked_by" field.
func (_u *MilkRecordUpdateOne) SetMilkedBy(v string) *MilkRecordUpdateOne {
	_u.mutation.SetMilkedBy(v)
	return _u
}

// SetNillableMilkedBy sets the "milked_by" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableMilkedBy(v *string) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetMilkedBy(*v)
	}
	return _u
}

// ClearMilkedBy clears the value of the "milked_by" field.
func (_u *MilkRecordUpdateOne) ClearMilkedBy() *MilkRecordUpdateOne {
	_u.mutation.ClearMilkedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MilkRecordUpdateOne) SetNotes(v string) *MilkRecordUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MilkRecordUpdateOne) SetNillableNotes(v *string) *MilkRecordUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MilkRecordUpdateOne) ClearNotes() *MilkRecordUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetGoatID sets the "goat" edge to the Goat entity by ID.
func (_u *MilkRecordUpdateOne) SetGoatID(id string) *MilkRecordUpdateOne {
	_u.mutation.SetGoatID(id)
	return _u
}

// SetGoat sets the "goat" edge to the Goat entity.
func (_u *MilkRecordUpdateOne) SetGoat(v *Goat) *MilkRecordUpdateOne {
	return _u.SetGoatID(v.ID)
}

// Mutation returns the MilkRecordMutation object of the builder.
func (_u *MilkRecordUpdateOne) Mutation() *MilkRecordMutation {
	return _u.mutation
}

// ClearGoat clears the "goat" edge to the Goat entity.
func (_u *MilkRecordUpdateOne) ClearGoat() *MilkRecordUpdateOne {
	_u.mutation.ClearGoat()
	return _u
}

// Where appends a list predicates to the MilkRecordUpdate builder.
func (_u *MilkRecordUpdateOne) Where(ps ...predicate.MilkRecord) *MilkRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MilkRecordUpdateOne) Select(field string, fields ...string) *MilkRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MilkRecord entity.
func (_u *MilkRecordUpdateOne) Save(ctx context.Context) (*MilkRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MilkRecordUpdateOne) SaveX(ctx context.Context) *MilkRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MilkRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MilkRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MilkRecordUpdateOne) check() error {
	if v, ok := _u.mutation.MilkingSession(); ok {
		if err := milkrecord.MilkingSessionValidator(v); err != nil {
			return &ValidationError{Name: "milking_session", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.milking_session": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VolumeLiters(); ok {
		if err := milkrecord.VolumeLitersValidator(v); err != nil {
			return &ValidationError{Name: "volume_liters", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.volume_liters": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FatContent(); ok {
		if err := milkrecord.FatContentValidator(v); err != nil {
			return &ValidationError{Name: "fat_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.fat_content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProteinContent(); ok {
		if err := milkrecord.ProteinContentValidator(v); err != nil {
			return &ValidationError{Name: "protein_content", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.protein_content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SomaticCellCount(); ok {
		if err := milkrecord.SomaticCellCountValidator(v); err != nil {
			return &ValidationError{Name: "somatic_cell_count", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.somatic_cell_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityGrade(); ok {
		if err := milkrecord.QualityGradeValidator(v); err != nil {
			return &ValidationError{Name: "quality_grade", err: fmt.Errorf(`ent: validator failed for field "MilkRecord.quality_grade": %w`, err)}
		}
	}
	if _u.mutation.GoatCleared() && len(_u.mutation.GoatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MilkRecord.goat"`)
	}
	return nil
}

func (_u *MilkRecordUpdateOne) sqlSave(ctx context.Context) (_node *MilkRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(milkrecord.Table, milkrecord.Columns, sqlgraph.NewFieldSpec(milkrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MilkRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, milkrecord.FieldID)
		for _, f := range fields {
			if !milkrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != milkrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MilkingTime(); ok {
		_spec.SetField(milkrecord.FieldMilkingTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MilkingSession(); ok {
		_spec.SetField(milkrecord.FieldMilkingSession, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VolumeLiters(); ok {
		_spec.SetField(milkrecord.FieldVolumeLiters, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolumeLiters(); ok {
		_spec.AddField(milkrecord.FieldVolumeLiters, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FatContent(); ok {
		_spec.SetField(milkrecord.FieldFatContent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFatContent(); ok {
		_spec.AddField(milkrecord.FieldFatContent, field.TypeFloat64, value)
	}
	if _u.mutation.FatContentCleared() {
		_spec.ClearField(milkrecord.FieldFatContent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProteinContent(); ok {
		_spec.SetField(milkrecord.FieldProteinContent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProteinContent(); ok {
		_spec.AddField(milkrecord.FieldProteinContent, field.TypeFloat64, value)
	}
	if _u.mutation.ProteinContentCleared() {
		_spec.ClearField(milkrecord.FieldProteinContent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SomaticCellCount(); ok {
		_spec.SetField(milkrecord.FieldSomaticCellCount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSomaticCellCount(); ok {
		_spec.AddField(milkrecord.FieldSomaticCellCount, field.TypeFloat64, value)
	}
	if _u.mutation.SomaticCellCountCleared() {
		_spec.ClearField(milkrecord.FieldSomaticCellCount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityGrade(); ok {
		_spec.SetField(milkrecord.FieldQualityGrade, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MilkedBy(); ok {
		_spec.SetField(milkrecord.FieldMilkedBy, field.TypeString, value)
	}
	if _u.mutation.MilkedByCleared() {
		_spec.ClearField(milkrecord.FieldMilkedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(milkrecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(milkrecord.FieldNotes, field.TypeString)
	}
	if _u.mutation.GoatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milkrecord.GoatTable,
			Columns: []string{milkrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milkrecord.GoatTable,
			Columns: []string{milkrecord.GoatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MilkRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{milkrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
