// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/farm/goat-manager/ent/breedingrecord"
	"github.com/farm/goat-manager/ent/farmoperation"
	"github.com/farm/goat-manager/ent/feedrecord"
	"github.com/farm/goat-manager/ent/goat"
	"github.com/farm/goat-manager/ent/healthrecord"
	"github.com/farm/goat-manager/ent/milkrecord"
	"github.com/farm/goat-manager/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	breedingrecordFields := schema.BreedingRecord{}.Fields()
	_ = breedingrecordFields
	// breedingrecordDescKidsBorn is the schema descriptor for kids_born field.
	breedingrecordDescKidsBorn := breedingrecordFields[5].Descriptor()
	// breedingrecord.KidsBornValidator is a validator for the "kids_born" field. It is called by the builders before save.
	breedingrecord.KidsBornValidator = breedingrecordDescKidsBorn.Validators[0].(func(int) error)
	// breedingrecordDescKidsAlive is the schema descriptor for kids_alive field.
	breedingrecordDescKidsAlive := breedingrecordFields[6].Descriptor()
	// breedingrecord.KidsAliveValidator is a validator for the "kids_alive" field. It is called by the builders before save.
	breedingrecord.KidsAliveValidator = breedingrecordDescKidsAlive.Validators[0].(func(int) error)
	// breedingrecordDescCreatedAt is the schema descriptor for created_at field.
	breedingrecordDescCreatedAt := breedingrecordFields[11].Descriptor()
	// breedingrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	breedingrecord.DefaultCreatedAt = breedingrecordDescCreatedAt.Default.(func() time.Time)
	// breedingrecordDescUpdatedAt is the schema descriptor for updated_at field.
	breedingrecordDescUpdatedAt := breedingrecordFields[12].Descriptor()
	// breedingrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	breedingrecord.DefaultUpdatedAt = breedingrecordDescUpdatedAt.Default.(func() time.Time)
	// breedingrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	breedingrecord.UpdateDefaultUpdatedAt = breedingrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	farmoperationFields := schema.FarmOperation{}.Fields()
	_ = farmoperationFields
	// farmoperationDescOperationDate is the schema descriptor for operation_date field.
	farmoperationDescOperationDate := farmoperationFields[0].Descriptor()
	// farmoperation.DefaultOperationDate holds the default value on creation for the operation_date field.
	farmoperation.DefaultOperationDate = farmoperationDescOperationDate.Default.(func() time.Time)
	// farmoperationDescCost is the schema descriptor for cost field.
	farmoperationDescCost := farmoperationFields[7].Descriptor()
	// farmoperation.CostValidator is a validator for the "cost" field. It is called by the builders before save.
	farmoperation.CostValidator = farmoperationDescCost.Validators[0].(func(float64) error)
	// farmoperationDescRevenue is the schema descriptor for revenue field.
	farmoperationDescRevenue := farmoperationFields[8].Descriptor()
	// farmoperation.RevenueValidator is a validator for the "revenue" field. It is called by the builders before save.
	farmoperation.RevenueValidator = farmoperationDescRevenue.Validators[0].(func(float64) error)
	// farmoperationDescCreatedAt is the schema descriptor for created_at field.
	farmoperationDescCreatedAt := farmoperationFields[11].Descriptor()
	// farmoperation.DefaultCreatedAt holds the default value on creation for the created_at field.
	farmoperation.DefaultCreatedAt = farmoperationDescCreatedAt.Default.(func() time.Time)
	// farmoperationDescUpdatedAt is the schema descriptor for updated_at field.
	farmoperationDescUpdatedAt := farmoperationFields[12].Descriptor()
	// farmoperation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	farmoperation.DefaultUpdatedAt = farmoperationDescUpdatedAt.Default.(func() time.Time)
	// farmoperation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	farmoperation.UpdateDefaultUpdatedAt = farmoperationDescUpdatedAt.UpdateDefault.(func() time.Time)
	feedrecordFields := schema.FeedRecord{}.Fields()
	_ = feedrecordFields
	// feedrecordDescFeedingDate is the schema descriptor for feeding_date field.
	feedrecordDescFeedingDate := feedrecordFields[0].Descriptor()
	// feedrecord.DefaultFeedingDate holds the default value on creation for the feeding_date field.
	feedrecord.DefaultFeedingDate = feedrecordDescFeedingDate.Default.(func() time.Time)
	// feedrecordDescQuantity is the schema descriptor for quantity field.
	feedrecordDescQuantity := feedrecordFields[3].Descriptor()
	// feedrecord.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	feedrecord.QuantityValidator = feedrecordDescQuantity.Validators[0].(func(float64) error)
	// feedrecordDescCostPerUnit is the schema descriptor for cost_per_unit field.
	feedrecordDescCostPerUnit := feedrecordFields[8].Descriptor()
	// feedrecord.CostPerUnitValidator is a validator for the "cost_per_unit" field. It is called by the builders before save.
	feedrecord.CostPerUnitValidator = feedrecordDescCostPerUnit.Validators[0].(func(float64) error)
	// feedrecordDescCreatedAt is the schema descriptor for created_at field.
	feedrecordDescCreatedAt := feedrecordFields[10].Descriptor()
	// feedrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	feedrecord.DefaultCreatedAt = feedrecordDescCreatedAt.Default.(func() time.Time)
	goatFields := schema.Goat{}.Fields()
	_ = goatFields
	// goatDescWeight is the schema descriptor for weight field.
	goatDescWeight := goatFields[5].Descriptor()
	// goat.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	goat.WeightValidator = goatDescWeight.Validators[0].(func(float64) error)
	// goatDescCreatedAt is the schema descriptor for created_at field.
	goatDescCreatedAt := goatFields[10].Descriptor()
	// goat.DefaultCreatedAt holds the default value on creation for the created_at field.
	goat.DefaultCreatedAt = goatDescCreatedAt.Default.(func() time.Time)
	// goatDescUpdatedAt is the schema descriptor for updated_at field.
	goatDescUpdatedAt := goatFields[11].Descriptor()
	// goat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	goat.DefaultUpdatedAt = goatDescUpdatedAt.Default.(func() time.Time)
	// goat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	goat.UpdateDefaultUpdatedAt = goatDescUpdatedAt.UpdateDefault.(func() time.Time)
	healthrecordFields := schema.HealthRecord{}.Fields()
	_ = healthrecordFields
	// healthrecordDescRecordDate is the schema descriptor for record_date field.
	healthrecordDescRecordDate := healthrecordFields[1].Descriptor()
	// healthrecord.DefaultRecordDate holds the default value on creation for the record_date field.
	healthrecord.DefaultRecordDate = healthrecordDescRecordDate.Default.(func() time.Time)
	// healthrecordDescWeight is the schema descriptor for weight field.
	healthrecordDescWeight := healthrecordFields[8].Descriptor()
	// healthrecord.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	healthrecord.WeightValidator = healthrecordDescWeight.Validators[0].(func(float64) error)
	// healthrecordDescCost is the schema descriptor for cost field.
	healthrecordDescCost := healthrecordFields[10].Descriptor()
	// healthrecord.CostValidator is a validator for the "cost" field. It is called by the builders before save.
	healthrecord.CostValidator = healthrecordDescCost.Validators[0].(func(float64) error)
	// healthrecordDescCreatedAt is the schema descriptor for created_at field.
	healthrecordDescCreatedAt := healthrecordFields[12].Descriptor()
	// healthrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	healthrecord.DefaultCreatedAt = healthrecordDescCreatedAt.Default.(func() time.Time)
	// healthrecordDescUpdatedAt is the schema descriptor for updated_at field.
	healthrecordDescUpdatedAt := healthrecordFields[13].Descriptor()
	// healthrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	healthrecord.DefaultUpdatedAt = healthrecordDescUpdatedAt.Default.(func() time.Time)
	// healthrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	healthrecord.UpdateDefaultUpdatedAt = healthrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	milkrecordFields := schema.MilkRecord{}.Fields()
	_ = milkrecordFields
	// milkrecordDescVolumeLiters is the schema descriptor for volume_liters field.
	milkrecordDescVolumeLiters := milkrecordFields[3].Descriptor()
	// milkrecord.VolumeLitersValidator is a validator for the "volume_liters" field. It is called by the builders before save.
	milkrecord.VolumeLitersValidator = milkrecordDescVolumeLiters.Validators[0].(func(float64) error)
	// milkrecordDescFatContent is the schema descriptor for fat_content field.
	milkrecordDescFatContent := milkrecordFields[4].Descriptor()
	// milkrecord.FatContentValidator is a validator for the "fat_content" field. It is called by the builders before save.
	milkrecord.FatContentValidator = func() func(float64) error {
		validators := milkrecordDescFatContent.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(fat_content float64) error {
			for _, fn := range fns {
				if err := fn(fat_content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// milkrecordDescProteinContent is the schema descriptor for protein_content field.
	milkrecordDescProteinContent := milkrecordFields[5].Descriptor()
	// milkrecord.ProteinContentValidator is a validator for the "protein_content" field. It is called by the builders before save.
	milkrecord.ProteinContentValidator = func() func(float64) error {
		validators := milkrecordDescProteinContent.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(protein_content float64) error {
			for _, fn := range fns {
				if err := fn(protein_content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// milkrecordDescSomaticCellCount is the schema descriptor for somatic_cell_count field.
	milkrecordDescSomaticCellCount := milkrecordFields[6].Descriptor()
	// milkrecord.SomaticCellCountValidator is a validator for the "somatic_cell_count" field. It is called by the builders before save.
	milkrecord.SomaticCellCountValidator = milkrecordDescSomaticCellCount.Validators[0].(func(float64) error)
	// milkrecordDescCreatedAt is the schema descriptor for created_at field.
	milkrecordDescCreatedAt := milkrecordFields[10].Descriptor()
	// milkrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	milkrecord.DefaultCreatedAt = milkrecordDescCreatedAt.Default.(func() time.Time)
}
