#!/usr/bin/env python3
"""
Tag Clustering with Embeddings and K-means

This module implements tag clustering for the fact extraction pipeline:
1. Extract all unique tags from the database
2. Generate embeddings using OpenAI API
3. Apply K-means clustering
4. Assign triples to top-3 relevant clusters
5. Store results back in database
"""

import json
import sqlite3
from collections import Counter
from dataclasses import dataclass
from typing import List, Dict, Tuple
import numpy as np
from openai import OpenAI

# Initialize OpenAI client
client = OpenAI()

@dataclass
class TagCluster:
    """Represents a cluster of related tags"""
    cluster_id: int
    tags: List[str]
    centroid: np.ndarray
    theme: str = ""  # Will be generated by LLM

@dataclass
class TagEmbedding:
    """Tag with its embedding vector"""
    tag: str
    embedding: np.ndarray
    cluster_id: int = -1

class TagClusterer:
    """Handles tag clustering operations"""
    
    def __init__(self, db_path: str = "fact_extraction.db", n_clusters: int = 30):
        self.db_path = db_path
        self.n_clusters = n_clusters
        self.tag_embeddings: List[TagEmbedding] = []
        self.clusters: List[TagCluster] = []
        
    def extract_tags(self) -> List[str]:
        """Extract all unique tags from database"""
        print("📊 Extracting tags from database...")
        
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Get all tags from triples
        cursor.execute("SELECT triple_tags FROM rdf_triples WHERE triple_tags IS NOT NULL")
        
        all_tags = []
        for (tags_json,) in cursor.fetchall():
            if tags_json:
                tags = json.loads(tags_json)
                all_tags.extend(tags)
        
        conn.close()
        
        # Count and get unique tags
        tag_counts = Counter(all_tags)
        unique_tags = list(tag_counts.keys())
        
        print(f"  ✓ Found {len(unique_tags)} unique tags from {len(all_tags)} total tag instances")
        print(f"  Top 10 tags: {', '.join([f'{tag}({count})' for tag, count in tag_counts.most_common(10)])}")
        
        return unique_tags
    
    def generate_embeddings(self, tags: List[str]) -> List[TagEmbedding]:
        """Generate embeddings for all tags using OpenAI API"""
        print(f"\n🔮 Generating embeddings for {len(tags)} tags...")
        
        # Batch tags for efficiency (OpenAI allows up to 2048 inputs)
        batch_size = 100
        embeddings = []
        
        for i in range(0, len(tags), batch_size):
            batch = tags[i:i+batch_size]
            print(f"  Processing batch {i//batch_size + 1}/{(len(tags)-1)//batch_size + 1}...")
            
            response = client.embeddings.create(
                model="text-embedding-ada-002",
                input=batch
            )
            
            for j, embedding_obj in enumerate(response.data):
                tag = batch[j]
                embedding = np.array(embedding_obj.embedding)
                embeddings.append(TagEmbedding(tag=tag, embedding=embedding))
        
        print(f"  ✓ Generated {len(embeddings)} embeddings (dimension: {len(embeddings[0].embedding)})")
        
        self.tag_embeddings = embeddings
        return embeddings
    
    def kmeans_clustering(self, embeddings: List[TagEmbedding], n_clusters: int) -> List[TagCluster]:
        """Apply K-means clustering to tag embeddings"""
        print(f"\n🎯 Applying K-means clustering (k={n_clusters})...")
        
        # Convert to numpy array
        X = np.array([e.embedding for e in embeddings])
        
        # Simple K-means implementation
        # Initialize centroids randomly
        np.random.seed(42)
        indices = np.random.choice(len(X), n_clusters, replace=False)
        centroids = X[indices].copy()
        
        max_iterations = 100
        for iteration in range(max_iterations):
            # Assign points to nearest centroid
            distances = np.array([[np.linalg.norm(x - c) for c in centroids] for x in X])
            assignments = np.argmin(distances, axis=1)
            
            # Update centroids
            new_centroids = np.array([X[assignments == k].mean(axis=0) if np.any(assignments == k) else centroids[k] 
                                       for k in range(n_clusters)])
            
            # Check convergence
            if np.allclose(centroids, new_centroids):
                print(f"  ✓ Converged after {iteration + 1} iterations")
                break
                
            centroids = new_centroids
        
        # Assign cluster IDs to embeddings
        for i, cluster_id in enumerate(assignments):
            embeddings[i].cluster_id = int(cluster_id)
        
        # Create cluster objects
        clusters = []
        for k in range(n_clusters):
            cluster_tags = [e.tag for e in embeddings if e.cluster_id == k]
            if cluster_tags:  # Only add non-empty clusters
                clusters.append(TagCluster(
                    cluster_id=k,
                    tags=cluster_tags,
                    centroid=centroids[k]
                ))
        
        print(f"  ✓ Created {len(clusters)} clusters")
        print(f"  Cluster sizes: min={min(len(c.tags) for c in clusters)}, "
              f"max={max(len(c.tags) for c in clusters)}, "
              f"avg={sum(len(c.tags) for c in clusters)/len(clusters):.1f}")
        
        self.clusters = clusters
        return clusters
    
    def generate_cluster_themes(self, clusters: List[TagCluster]) -> List[TagCluster]:
        """Use LLM to generate descriptive themes for each cluster"""
        print(f"\n🏷️  Generating cluster themes using LLM...")
        
        for i, cluster in enumerate(clusters):
            # Show top tags (up to 15)
            top_tags = cluster.tags[:15]
            tags_str = ", ".join(top_tags)
            
            prompt = f"""Given these related tags from a document analysis system, provide a concise 2-4 word theme that describes what they have in common:

Tags: {tags_str}

Respond with ONLY the theme, nothing else."""
            
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=20
            )
            
            theme = response.choices[0].message.content.strip()
            cluster.theme = theme
            
            print(f"  Cluster {i}: {theme} ({len(cluster.tags)} tags)")
        
        print(f"  ✓ Generated themes for {len(clusters)} clusters")
        return clusters
    
    def assign_triples_to_clusters(self) -> int:
        """Assign each triple to its top-3 relevant clusters based on tags"""
        print(f"\n📌 Assigning triples to top-3 clusters...")
        
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Add cluster columns if they don't exist
        try:
            cursor.execute("ALTER TABLE rdf_triples ADD COLUMN cluster_ids TEXT")
            cursor.execute("ALTER TABLE rdf_triples ADD COLUMN cluster_themes TEXT")
        except sqlite3.OperationalError:
            # Columns already exist
            pass
        
        # Get all triples with tags
        cursor.execute("SELECT id, triple_tags FROM rdf_triples WHERE triple_tags IS NOT NULL")
        triples = cursor.fetchall()
        
        updated_count = 0
        for triple_id, tags_json in triples:
            if not tags_json:
                continue
                
            tags = json.loads(tags_json)
            
            # Find cluster IDs for these tags
            cluster_scores = Counter()
            for tag in tags:
                # Find which cluster this tag belongs to
                for embedding in self.tag_embeddings:
                    if embedding.tag == tag and embedding.cluster_id >= 0:
                        cluster_scores[embedding.cluster_id] += 1
                        break
            
            # Get top 3 clusters
            top_clusters = cluster_scores.most_common(3)
            if top_clusters:
                cluster_ids = [str(c[0]) for c in top_clusters]
                cluster_themes = [self.clusters[c[0]].theme for c in top_clusters if c[0] < len(self.clusters)]
                
                cursor.execute("""
                    UPDATE rdf_triples 
                    SET cluster_ids = ?, cluster_themes = ?
                    WHERE id = ?
                """, (json.dumps(cluster_ids), json.dumps(cluster_themes), triple_id))
                
                updated_count += 1
        
        conn.commit()
        conn.close()
        
        print(f"  ✓ Updated {updated_count} triples with cluster assignments")
        return updated_count
    
    def save_clusters_to_file(self, output_path: str = "tag_clusters.json"):
        """Save cluster information to JSON file"""
        print(f"\n💾 Saving clusters to {output_path}...")
        
        clusters_data = []
        for cluster in self.clusters:
            clusters_data.append({
                "cluster_id": cluster.cluster_id,
                "theme": cluster.theme,
                "tag_count": len(cluster.tags),
                "tags": cluster.tags
            })
        
        with open(output_path, 'w') as f:
            json.dump(clusters_data, f, indent=2)
        
        print(f"  ✓ Saved {len(clusters_data)} clusters")
    
    def run_full_pipeline(self):
        """Execute the complete clustering pipeline"""
        print("=" * 80)
        print("TAG CLUSTERING PIPELINE")
        print("=" * 80)
        
        # Step 1: Extract tags
        tags = self.extract_tags()
        
        # Step 2: Generate embeddings
        embeddings = self.generate_embeddings(tags)
        
        # Step 3: Cluster tags
        clusters = self.kmeans_clustering(embeddings, self.n_clusters)
        
        # Step 4: Generate themes
        clusters = self.generate_cluster_themes(clusters)
        
        # Step 5: Assign triples to clusters
        self.assign_triples_to_clusters()
        
        # Step 6: Save results
        self.save_clusters_to_file()
        
        print("\n" + "=" * 80)
        print("✓ CLUSTERING COMPLETE")
        print("=" * 80)
        
        # Print summary
        print(f"\nSummary:")
        print(f"  - Unique tags: {len(tags)}")
        print(f"  - Clusters created: {len(clusters)}")
        print(f"  - Avg tags per cluster: {len(tags)/len(clusters):.1f}")
        print(f"\nTop 10 cluster themes:")
        sorted_clusters = sorted(clusters, key=lambda c: len(c.tags), reverse=True)
        for i, cluster in enumerate(sorted_clusters[:10], 1):
            print(f"  {i}. {cluster.theme} ({len(cluster.tags)} tags)")

def main():
    clusterer = TagClusterer(db_path="fact_extraction.db", n_clusters=30)
    clusterer.run_full_pipeline()

if __name__ == "__main__":
    main()
