(load "prolog-standalone.lisp")

(<- (parent tom bob))
(<- (parent tom liz))
(<- (parent bob ann))
(<- (grandparent ?gp ?gc) (parent ?gp ?p) (parent ?p ?gc))

(let* ((goals (read-from-string "((grandparent tom ?gc))"))
       (vars (variables-in goals))
       (solutions (prove-all goals no-bindings)))
  (format t "~%PROLOG-RESULTS-START~%")
  (if (null solutions)
      (format t "NO-SOLUTIONS~%")
      (dolist (solution solutions)
        (format t "SOLUTION-START~%")
        (dolist (var vars)
          (let ((val (subst-bindings solution var)))
            (format t "~A=~S~%" var val)))
        (format t "SOLUTION-END~%")))
  (format t "PROLOG-RESULTS-END~%"))
