// Code generated by tygo. DO NOT EDIT.

//////////
// source: user.go

/**
 * User represents a user in the system
 */
export interface User {
  id: string;
  username: string;
  email: string;
  createdAt: string;
  isActive: boolean;
}
/**
 * UserCreateParams contains parameters for creating a new user
 */
export interface UserCreateParams {
  username: string;
  email: string;
}
