// Code generated by ent, DO NOT EDIT.

package healthrecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the healthrecord type in the database.
	Label = "health_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGoatTag holds the string denoting the goat_tag field in the database.
	FieldGoatTag = "goat_tag"
	// FieldRecordDate holds the string denoting the record_date field in the database.
	FieldRecordDate = "record_date"
	// FieldRecordType holds the string denoting the record_type field in the database.
	FieldRecordType = "record_type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldVeterinarian holds the string denoting the veterinarian field in the database.
	FieldVeterinarian = "veterinarian"
	// FieldMedication holds the string denoting the medication field in the database.
	FieldMedication = "medication"
	// FieldDosage holds the string denoting the dosage field in the database.
	FieldDosage = "dosage"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldNextDueDate holds the string denoting the next_due_date field in the database.
	FieldNextDueDate = "next_due_date"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGoat holds the string denoting the goat edge name in mutations.
	EdgeGoat = "goat"
	// GoatFieldID holds the string denoting the ID field of the Goat.
	GoatFieldID = "tag_id"
	// Table holds the table name of the healthrecord in the database.
	Table = "health_records"
	// GoatTable is the table that holds the goat relation/edge.
	GoatTable = "health_records"
	// GoatInverseTable is the table name for the Goat entity.
	// It exists in this package in order to avoid circular dependency with the "goat" package.
	GoatInverseTable = "goats"
	// GoatColumn is the table column denoting the goat relation/edge.
	GoatColumn = "goat_tag"
)

// Columns holds all SQL columns for healthrecord fields.
var Columns = []string{
	FieldID,
	FieldGoatTag,
	FieldRecordDate,
	FieldRecordType,
	FieldDescription,
	FieldVeterinarian,
	FieldMedication,
	FieldDosage,
	FieldTemperature,
	FieldWeight,
	FieldNextDueDate,
	FieldCost,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecordDate holds the default value on creation for the "record_date" field.
	DefaultRecordDate func() time.Time
	// WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	WeightValidator func(float64) error
	// CostValidator is a validator for the "cost" field. It is called by the builders before save.
	CostValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// RecordType defines the type for the "record_type" enum field.
type RecordType string

// RecordType values.
const (
	RecordTypeVaccination RecordType = "vaccination"
	RecordTypeTreatment   RecordType = "treatment"
	RecordTypeCheckup     RecordType = "checkup"
	RecordTypeInjury      RecordType = "injury"
	RecordTypeIllness     RecordType = "illness"
	RecordTypeMedication  RecordType = "medication"
	RecordTypeDeworming   RecordType = "deworming"
	RecordTypeHoofTrim    RecordType = "hoof_trim"
)

func (rt RecordType) String() string {
	return string(rt)
}

// RecordTypeValidator is a validator for the "record_type" field enum values. It is called by the builders before save.
func RecordTypeValidator(rt RecordType) error {
	switch rt {
	case RecordTypeVaccination, RecordTypeTreatment, RecordTypeCheckup, RecordTypeInjury, RecordTypeIllness, RecordTypeMedication, RecordTypeDeworming, RecordTypeHoofTrim:
		return nil
	default:
		return fmt.Errorf("healthrecord: invalid enum value for record_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the HealthRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGoatTag orders the results by the goat_tag field.
func ByGoatTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoatTag, opts...).ToFunc()
}

// ByRecordDate orders the results by the record_date field.
func ByRecordDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordDate, opts...).ToFunc()
}

// ByRecordType orders the results by the record_type field.
func ByRecordType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByVeterinarian orders the results by the veterinarian field.
func ByVeterinarian(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVeterinarian, opts...).ToFunc()
}

// ByMedication orders the results by the medication field.
func ByMedication(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedication, opts...).ToFunc()
}

// ByDosage orders the results by the dosage field.
func ByDosage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDosage, opts...).ToFunc()
}

// ByTemperature orders the results by the temperature field.
func ByTemperature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperature, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByNextDueDate orders the results by the next_due_date field.
func ByNextDueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDueDate, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGoatField orders the results by goat field.
func ByGoatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoatStep(), sql.OrderByField(field, opts...))
	}
}
func newGoatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoatInverseTable, GoatFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GoatTable, GoatColumn),
	)
}
