// Code generated by ent, DO NOT EDIT.

package healthrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/farm/goat-manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldID, id))
}

// GoatTag applies equality check predicate on the "goat_tag" field. It's identical to GoatTagEQ.
func GoatTag(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldGoatTag, v))
}

// RecordDate applies equality check predicate on the "record_date" field. It's identical to RecordDateEQ.
func RecordDate(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldRecordDate, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldDescription, v))
}

// Veterinarian applies equality check predicate on the "veterinarian" field. It's identical to VeterinarianEQ.
func Veterinarian(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldVeterinarian, v))
}

// Medication applies equality check predicate on the "medication" field. It's identical to MedicationEQ.
func Medication(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldMedication, v))
}

// Dosage applies equality check predicate on the "dosage" field. It's identical to DosageEQ.
func Dosage(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldDosage, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldTemperature, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldWeight, v))
}

// NextDueDate applies equality check predicate on the "next_due_date" field. It's identical to NextDueDateEQ.
func NextDueDate(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldNextDueDate, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldCost, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// GoatTagEQ applies the EQ predicate on the "goat_tag" field.
func GoatTagEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldGoatTag, v))
}

// GoatTagNEQ applies the NEQ predicate on the "goat_tag" field.
func GoatTagNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldGoatTag, v))
}

// GoatTagIn applies the In predicate on the "goat_tag" field.
func GoatTagIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldGoatTag, vs...))
}

// GoatTagNotIn applies the NotIn predicate on the "goat_tag" field.
func GoatTagNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldGoatTag, vs...))
}

// GoatTagGT applies the GT predicate on the "goat_tag" field.
func GoatTagGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldGoatTag, v))
}

// GoatTagGTE applies the GTE predicate on the "goat_tag" field.
func GoatTagGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldGoatTag, v))
}

// GoatTagLT applies the LT predicate on the "goat_tag" field.
func GoatTagLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldGoatTag, v))
}

// GoatTagLTE applies the LTE predicate on the "goat_tag" field.
func GoatTagLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldGoatTag, v))
}

// GoatTagContains applies the Contains predicate on the "goat_tag" field.
func GoatTagContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldGoatTag, v))
}

// GoatTagHasPrefix applies the HasPrefix predicate on the "goat_tag" field.
func GoatTagHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldGoatTag, v))
}

// GoatTagHasSuffix applies the HasSuffix predicate on the "goat_tag" field.
func GoatTagHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldGoatTag, v))
}

// GoatTagEqualFold applies the EqualFold predicate on the "goat_tag" field.
func GoatTagEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldGoatTag, v))
}

// GoatTagContainsFold applies the ContainsFold predicate on the "goat_tag" field.
func GoatTagContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldGoatTag, v))
}

// RecordDateEQ applies the EQ predicate on the "record_date" field.
func RecordDateEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldRecordDate, v))
}

// RecordDateNEQ applies the NEQ predicate on the "record_date" field.
func RecordDateNEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldRecordDate, v))
}

// RecordDateIn applies the In predicate on the "record_date" field.
func RecordDateIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldRecordDate, vs...))
}

// RecordDateNotIn applies the NotIn predicate on the "record_date" field.
func RecordDateNotIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldRecordDate, vs...))
}

// RecordDateGT applies the GT predicate on the "record_date" field.
func RecordDateGT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldRecordDate, v))
}

// RecordDateGTE applies the GTE predicate on the "record_date" field.
func RecordDateGTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldRecordDate, v))
}

// RecordDateLT applies the LT predicate on the "record_date" field.
func RecordDateLT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldRecordDate, v))
}

// RecordDateLTE applies the LTE predicate on the "record_date" field.
func RecordDateLTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldRecordDate, v))
}

// RecordTypeEQ applies the EQ predicate on the "record_type" field.
func RecordTypeEQ(v RecordType) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldRecordType, v))
}

// RecordTypeNEQ applies the NEQ predicate on the "record_type" field.
func RecordTypeNEQ(v RecordType) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldRecordType, v))
}

// RecordTypeIn applies the In predicate on the "record_type" field.
func RecordTypeIn(vs ...RecordType) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldRecordType, vs...))
}

// RecordTypeNotIn applies the NotIn predicate on the "record_type" field.
func RecordTypeNotIn(vs ...RecordType) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldRecordType, vs...))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldDescription, v))
}

// VeterinarianEQ applies the EQ predicate on the "veterinarian" field.
func VeterinarianEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldVeterinarian, v))
}

// VeterinarianNEQ applies the NEQ predicate on the "veterinarian" field.
func VeterinarianNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldVeterinarian, v))
}

// VeterinarianIn applies the In predicate on the "veterinarian" field.
func VeterinarianIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldVeterinarian, vs...))
}

// VeterinarianNotIn applies the NotIn predicate on the "veterinarian" field.
func VeterinarianNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldVeterinarian, vs...))
}

// VeterinarianGT applies the GT predicate on the "veterinarian" field.
func VeterinarianGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldVeterinarian, v))
}

// VeterinarianGTE applies the GTE predicate on the "veterinarian" field.
func VeterinarianGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldVeterinarian, v))
}

// VeterinarianLT applies the LT predicate on the "veterinarian" field.
func VeterinarianLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldVeterinarian, v))
}

// VeterinarianLTE applies the LTE predicate on the "veterinarian" field.
func VeterinarianLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldVeterinarian, v))
}

// VeterinarianContains applies the Contains predicate on the "veterinarian" field.
func VeterinarianContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldVeterinarian, v))
}

// VeterinarianHasPrefix applies the HasPrefix predicate on the "veterinarian" field.
func VeterinarianHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldVeterinarian, v))
}

// VeterinarianHasSuffix applies the HasSuffix predicate on the "veterinarian" field.
func VeterinarianHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldVeterinarian, v))
}

// VeterinarianIsNil applies the IsNil predicate on the "veterinarian" field.
func VeterinarianIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldVeterinarian))
}

// VeterinarianNotNil applies the NotNil predicate on the "veterinarian" field.
func VeterinarianNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldVeterinarian))
}

// VeterinarianEqualFold applies the EqualFold predicate on the "veterinarian" field.
func VeterinarianEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldVeterinarian, v))
}

// VeterinarianContainsFold applies the ContainsFold predicate on the "veterinarian" field.
func VeterinarianContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldVeterinarian, v))
}

// MedicationEQ applies the EQ predicate on the "medication" field.
func MedicationEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldMedication, v))
}

// MedicationNEQ applies the NEQ predicate on the "medication" field.
func MedicationNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldMedication, v))
}

// MedicationIn applies the In predicate on the "medication" field.
func MedicationIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldMedication, vs...))
}

// MedicationNotIn applies the NotIn predicate on the "medication" field.
func MedicationNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldMedication, vs...))
}

// MedicationGT applies the GT predicate on the "medication" field.
func MedicationGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldMedication, v))
}

// MedicationGTE applies the GTE predicate on the "medication" field.
func MedicationGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldMedication, v))
}

// MedicationLT applies the LT predicate on the "medication" field.
func MedicationLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldMedication, v))
}

// MedicationLTE applies the LTE predicate on the "medication" field.
func MedicationLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldMedication, v))
}

// MedicationContains applies the Contains predicate on the "medication" field.
func MedicationContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldMedication, v))
}

// MedicationHasPrefix applies the HasPrefix predicate on the "medication" field.
func MedicationHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldMedication, v))
}

// MedicationHasSuffix applies the HasSuffix predicate on the "medication" field.
func MedicationHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldMedication, v))
}

// MedicationIsNil applies the IsNil predicate on the "medication" field.
func MedicationIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldMedication))
}

// MedicationNotNil applies the NotNil predicate on the "medication" field.
func MedicationNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldMedication))
}

// MedicationEqualFold applies the EqualFold predicate on the "medication" field.
func MedicationEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldMedication, v))
}

// MedicationContainsFold applies the ContainsFold predicate on the "medication" field.
func MedicationContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldMedication, v))
}

// DosageEQ applies the EQ predicate on the "dosage" field.
func DosageEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldDosage, v))
}

// DosageNEQ applies the NEQ predicate on the "dosage" field.
func DosageNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldDosage, v))
}

// DosageIn applies the In predicate on the "dosage" field.
func DosageIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldDosage, vs...))
}

// DosageNotIn applies the NotIn predicate on the "dosage" field.
func DosageNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldDosage, vs...))
}

// DosageGT applies the GT predicate on the "dosage" field.
func DosageGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldDosage, v))
}

// DosageGTE applies the GTE predicate on the "dosage" field.
func DosageGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldDosage, v))
}

// DosageLT applies the LT predicate on the "dosage" field.
func DosageLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldDosage, v))
}

// DosageLTE applies the LTE predicate on the "dosage" field.
func DosageLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldDosage, v))
}

// DosageContains applies the Contains predicate on the "dosage" field.
func DosageContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldDosage, v))
}

// DosageHasPrefix applies the HasPrefix predicate on the "dosage" field.
func DosageHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldDosage, v))
}

// DosageHasSuffix applies the HasSuffix predicate on the "dosage" field.
func DosageHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldDosage, v))
}

// DosageIsNil applies the IsNil predicate on the "dosage" field.
func DosageIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldDosage))
}

// DosageNotNil applies the NotNil predicate on the "dosage" field.
func DosageNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldDosage))
}

// DosageEqualFold applies the EqualFold predicate on the "dosage" field.
func DosageEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldDosage, v))
}

// DosageContainsFold applies the ContainsFold predicate on the "dosage" field.
func DosageContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldDosage, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldTemperature, v))
}

// TemperatureIsNil applies the IsNil predicate on the "temperature" field.
func TemperatureIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldTemperature))
}

// TemperatureNotNil applies the NotNil predicate on the "temperature" field.
func TemperatureNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldTemperature))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldWeight, v))
}

// WeightIsNil applies the IsNil predicate on the "weight" field.
func WeightIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldWeight))
}

// WeightNotNil applies the NotNil predicate on the "weight" field.
func WeightNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldWeight))
}

// NextDueDateEQ applies the EQ predicate on the "next_due_date" field.
func NextDueDateEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldNextDueDate, v))
}

// NextDueDateNEQ applies the NEQ predicate on the "next_due_date" field.
func NextDueDateNEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldNextDueDate, v))
}

// NextDueDateIn applies the In predicate on the "next_due_date" field.
func NextDueDateIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldNextDueDate, vs...))
}

// NextDueDateNotIn applies the NotIn predicate on the "next_due_date" field.
func NextDueDateNotIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldNextDueDate, vs...))
}

// NextDueDateGT applies the GT predicate on the "next_due_date" field.
func NextDueDateGT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldNextDueDate, v))
}

// NextDueDateGTE applies the GTE predicate on the "next_due_date" field.
func NextDueDateGTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldNextDueDate, v))
}

// NextDueDateLT applies the LT predicate on the "next_due_date" field.
func NextDueDateLT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldNextDueDate, v))
}

// NextDueDateLTE applies the LTE predicate on the "next_due_date" field.
func NextDueDateLTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldNextDueDate, v))
}

// NextDueDateIsNil applies the IsNil predicate on the "next_due_date" field.
func NextDueDateIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldNextDueDate))
}

// NextDueDateNotNil applies the NotNil predicate on the "next_due_date" field.
func NextDueDateNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldNextDueDate))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldCost, v))
}

// CostIsNil applies the IsNil predicate on the "cost" field.
func CostIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldCost))
}

// CostNotNil applies the NotNil predicate on the "cost" field.
func CostNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldCost))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HealthRecord {
	return predicate.HealthRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGoat applies the HasEdge predicate on the "goat" edge.
func HasGoat() predicate.HealthRecord {
	return predicate.HealthRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GoatTable, GoatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGoatWith applies the HasEdge predicate on the "goat" edge with a given conditions (other predicates).
func HasGoatWith(preds ...predicate.Goat) predicate.HealthRecord {
	return predicate.HealthRecord(func(s *sql.Selector) {
		step := newGoatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HealthRecord) predicate.HealthRecord {
	return predicate.HealthRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HealthRecord) predicate.HealthRecord {
	return predicate.HealthRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HealthRecord) predicate.HealthRecord {
	return predicate.HealthRecord(sql.NotPredicates(p))
}
