// Generated TypeScript definitions for Go types
// This would normally be generated by tygo

export interface User {
    id: string;
    username: string;
    email: string;
    createdAt: string;
    isActive: boolean;
}

export interface UserCreateParams {
    username: string;
    email: string;
}

// Function signature for CreateUser
export declare function CreateUser(params: UserCreateParams): User | Error;
