// Code generated by ent, DO NOT EDIT.

package turnmetadata

import (
	"turn-inspector/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLTE(FieldID, id))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldSource, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldKey, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldValue, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContainsFold(FieldSource, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContainsFold(FieldKey, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.FieldContainsFold(FieldValue, v))
}

// HasTurn applies the HasEdge predicate on the "turn" edge.
func HasTurn() predicate.TurnMetadata {
	return predicate.TurnMetadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TurnTable, TurnColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTurnWith applies the HasEdge predicate on the "turn" edge with a given conditions (other predicates).
func HasTurnWith(preds ...predicate.Turn) predicate.TurnMetadata {
	return predicate.TurnMetadata(func(s *sql.Selector) {
		step := newTurnStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TurnMetadata) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TurnMetadata) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TurnMetadata) predicate.TurnMetadata {
	return predicate.TurnMetadata(sql.NotPredicates(p))
}
