// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"turn-inspector/ent/block"
	"turn-inspector/ent/blockmetadata"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BlockMetadata is the model entity for the BlockMetadata schema.
type BlockMetadata struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlockMetadataQuery when eager-loading is set.
	Edges          BlockMetadataEdges `json:"edges"`
	block_metadata *int
	selectValues   sql.SelectValues
}

// BlockMetadataEdges holds the relations/edges for other nodes in the graph.
type BlockMetadataEdges struct {
	// Block holds the value of the block edge.
	Block *Block `json:"block,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BlockOrErr returns the Block value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlockMetadataEdges) BlockOrErr() (*Block, error) {
	if e.Block != nil {
		return e.Block, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: block.Label}
	}
	return nil, &NotLoadedError{edge: "block"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlockMetadata) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blockmetadata.FieldID:
			values[i] = new(sql.NullInt64)
		case blockmetadata.FieldSource, blockmetadata.FieldKey, blockmetadata.FieldValue:
			values[i] = new(sql.NullString)
		case blockmetadata.ForeignKeys[0]: // block_metadata
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlockMetadata fields.
func (_m *BlockMetadata) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blockmetadata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case blockmetadata.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case blockmetadata.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case blockmetadata.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case blockmetadata.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field block_metadata", value)
			} else if value.Valid {
				_m.block_metadata = new(int)
				*_m.block_metadata = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the BlockMetadata.
// This includes values selected through modifiers, order, etc.
func (_m *BlockMetadata) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBlock queries the "block" edge of the BlockMetadata entity.
func (_m *BlockMetadata) QueryBlock() *BlockQuery {
	return NewBlockMetadataClient(_m.config).QueryBlock(_m)
}

// Update returns a builder for updating this BlockMetadata.
// Note that you need to call BlockMetadata.Unwrap() before calling this method if this BlockMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BlockMetadata) Update() *BlockMetadataUpdateOne {
	return NewBlockMetadataClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BlockMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BlockMetadata) Unwrap() *BlockMetadata {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlockMetadata is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BlockMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("BlockMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// BlockMetadataSlice is a parsable slice of BlockMetadata.
type BlockMetadataSlice []*BlockMetadata
