// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"turn-inspector/ent/migrate"

	"turn-inspector/ent/block"
	"turn-inspector/ent/blockmetadata"
	"turn-inspector/ent/turn"
	"turn-inspector/ent/turnmetadata"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Block is the client for interacting with the Block builders.
	Block *BlockClient
	// BlockMetadata is the client for interacting with the BlockMetadata builders.
	BlockMetadata *BlockMetadataClient
	// Turn is the client for interacting with the Turn builders.
	Turn *TurnClient
	// TurnMetadata is the client for interacting with the TurnMetadata builders.
	TurnMetadata *TurnMetadataClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Block = NewBlockClient(c.config)
	c.BlockMetadata = NewBlockMetadataClient(c.config)
	c.Turn = NewTurnClient(c.config)
	c.TurnMetadata = NewTurnMetadataClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Block:         NewBlockClient(cfg),
		BlockMetadata: NewBlockMetadataClient(cfg),
		Turn:          NewTurnClient(cfg),
		TurnMetadata:  NewTurnMetadataClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Block:         NewBlockClient(cfg),
		BlockMetadata: NewBlockMetadataClient(cfg),
		Turn:          NewTurnClient(cfg),
		TurnMetadata:  NewTurnMetadataClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Block.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Block.Use(hooks...)
	c.BlockMetadata.Use(hooks...)
	c.Turn.Use(hooks...)
	c.TurnMetadata.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Block.Intercept(interceptors...)
	c.BlockMetadata.Intercept(interceptors...)
	c.Turn.Intercept(interceptors...)
	c.TurnMetadata.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BlockMutation:
		return c.Block.mutate(ctx, m)
	case *BlockMetadataMutation:
		return c.BlockMetadata.mutate(ctx, m)
	case *TurnMutation:
		return c.Turn.mutate(ctx, m)
	case *TurnMetadataMutation:
		return c.TurnMetadata.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BlockClient is a client for the Block schema.
type BlockClient struct {
	config
}

// NewBlockClient returns a client for the Block from the given config.
func NewBlockClient(c config) *BlockClient {
	return &BlockClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `block.Hooks(f(g(h())))`.
func (c *BlockClient) Use(hooks ...Hook) {
	c.hooks.Block = append(c.hooks.Block, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `block.Intercept(f(g(h())))`.
func (c *BlockClient) Intercept(interceptors ...Interceptor) {
	c.inters.Block = append(c.inters.Block, interceptors...)
}

// Create returns a builder for creating a Block entity.
func (c *BlockClient) Create() *BlockCreate {
	mutation := newBlockMutation(c.config, OpCreate)
	return &BlockCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Block entities.
func (c *BlockClient) CreateBulk(builders ...*BlockCreate) *BlockCreateBulk {
	return &BlockCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BlockClient) MapCreateBulk(slice any, setFunc func(*BlockCreate, int)) *BlockCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BlockCreateBulk{err: fmt.Errorf("calling to BlockClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BlockCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BlockCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Block.
func (c *BlockClient) Update() *BlockUpdate {
	mutation := newBlockMutation(c.config, OpUpdate)
	return &BlockUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BlockClient) UpdateOne(_m *Block) *BlockUpdateOne {
	mutation := newBlockMutation(c.config, OpUpdateOne, withBlock(_m))
	return &BlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BlockClient) UpdateOneID(id int) *BlockUpdateOne {
	mutation := newBlockMutation(c.config, OpUpdateOne, withBlockID(id))
	return &BlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Block.
func (c *BlockClient) Delete() *BlockDelete {
	mutation := newBlockMutation(c.config, OpDelete)
	return &BlockDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BlockClient) DeleteOne(_m *Block) *BlockDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BlockClient) DeleteOneID(id int) *BlockDeleteOne {
	builder := c.Delete().Where(block.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BlockDeleteOne{builder}
}

// Query returns a query builder for Block.
func (c *BlockClient) Query() *BlockQuery {
	return &BlockQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBlock},
		inters: c.Interceptors(),
	}
}

// Get returns a Block entity by its id.
func (c *BlockClient) Get(ctx context.Context, id int) (*Block, error) {
	return c.Query().Where(block.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BlockClient) GetX(ctx context.Context, id int) *Block {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTurn queries the turn edge of a Block.
func (c *BlockClient) QueryTurn(_m *Block) *TurnQuery {
	query := (&TurnClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(block.Table, block.FieldID, id),
			sqlgraph.To(turn.Table, turn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, block.TurnTable, block.TurnColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMetadata queries the metadata edge of a Block.
func (c *BlockClient) QueryMetadata(_m *Block) *BlockMetadataQuery {
	query := (&BlockMetadataClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(block.Table, block.FieldID, id),
			sqlgraph.To(blockmetadata.Table, blockmetadata.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, block.MetadataTable, block.MetadataColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BlockClient) Hooks() []Hook {
	return c.hooks.Block
}

// Interceptors returns the client interceptors.
func (c *BlockClient) Interceptors() []Interceptor {
	return c.inters.Block
}

func (c *BlockClient) mutate(ctx context.Context, m *BlockMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BlockCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BlockUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BlockDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Block mutation op: %q", m.Op())
	}
}

// BlockMetadataClient is a client for the BlockMetadata schema.
type BlockMetadataClient struct {
	config
}

// NewBlockMetadataClient returns a client for the BlockMetadata from the given config.
func NewBlockMetadataClient(c config) *BlockMetadataClient {
	return &BlockMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `blockmetadata.Hooks(f(g(h())))`.
func (c *BlockMetadataClient) Use(hooks ...Hook) {
	c.hooks.BlockMetadata = append(c.hooks.BlockMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `blockmetadata.Intercept(f(g(h())))`.
func (c *BlockMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.BlockMetadata = append(c.inters.BlockMetadata, interceptors...)
}

// Create returns a builder for creating a BlockMetadata entity.
func (c *BlockMetadataClient) Create() *BlockMetadataCreate {
	mutation := newBlockMetadataMutation(c.config, OpCreate)
	return &BlockMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BlockMetadata entities.
func (c *BlockMetadataClient) CreateBulk(builders ...*BlockMetadataCreate) *BlockMetadataCreateBulk {
	return &BlockMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BlockMetadataClient) MapCreateBulk(slice any, setFunc func(*BlockMetadataCreate, int)) *BlockMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BlockMetadataCreateBulk{err: fmt.Errorf("calling to BlockMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BlockMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BlockMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BlockMetadata.
func (c *BlockMetadataClient) Update() *BlockMetadataUpdate {
	mutation := newBlockMetadataMutation(c.config, OpUpdate)
	return &BlockMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BlockMetadataClient) UpdateOne(_m *BlockMetadata) *BlockMetadataUpdateOne {
	mutation := newBlockMetadataMutation(c.config, OpUpdateOne, withBlockMetadata(_m))
	return &BlockMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BlockMetadataClient) UpdateOneID(id int) *BlockMetadataUpdateOne {
	mutation := newBlockMetadataMutation(c.config, OpUpdateOne, withBlockMetadataID(id))
	return &BlockMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BlockMetadata.
func (c *BlockMetadataClient) Delete() *BlockMetadataDelete {
	mutation := newBlockMetadataMutation(c.config, OpDelete)
	return &BlockMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BlockMetadataClient) DeleteOne(_m *BlockMetadata) *BlockMetadataDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BlockMetadataClient) DeleteOneID(id int) *BlockMetadataDeleteOne {
	builder := c.Delete().Where(blockmetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BlockMetadataDeleteOne{builder}
}

// Query returns a query builder for BlockMetadata.
func (c *BlockMetadataClient) Query() *BlockMetadataQuery {
	return &BlockMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBlockMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a BlockMetadata entity by its id.
func (c *BlockMetadataClient) Get(ctx context.Context, id int) (*BlockMetadata, error) {
	return c.Query().Where(blockmetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BlockMetadataClient) GetX(ctx context.Context, id int) *BlockMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBlock queries the block edge of a BlockMetadata.
func (c *BlockMetadataClient) QueryBlock(_m *BlockMetadata) *BlockQuery {
	query := (&BlockClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blockmetadata.Table, blockmetadata.FieldID, id),
			sqlgraph.To(block.Table, block.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blockmetadata.BlockTable, blockmetadata.BlockColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BlockMetadataClient) Hooks() []Hook {
	return c.hooks.BlockMetadata
}

// Interceptors returns the client interceptors.
func (c *BlockMetadataClient) Interceptors() []Interceptor {
	return c.inters.BlockMetadata
}

func (c *BlockMetadataClient) mutate(ctx context.Context, m *BlockMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BlockMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BlockMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BlockMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BlockMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BlockMetadata mutation op: %q", m.Op())
	}
}

// TurnClient is a client for the Turn schema.
type TurnClient struct {
	config
}

// NewTurnClient returns a client for the Turn from the given config.
func NewTurnClient(c config) *TurnClient {
	return &TurnClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `turn.Hooks(f(g(h())))`.
func (c *TurnClient) Use(hooks ...Hook) {
	c.hooks.Turn = append(c.hooks.Turn, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `turn.Intercept(f(g(h())))`.
func (c *TurnClient) Intercept(interceptors ...Interceptor) {
	c.inters.Turn = append(c.inters.Turn, interceptors...)
}

// Create returns a builder for creating a Turn entity.
func (c *TurnClient) Create() *TurnCreate {
	mutation := newTurnMutation(c.config, OpCreate)
	return &TurnCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Turn entities.
func (c *TurnClient) CreateBulk(builders ...*TurnCreate) *TurnCreateBulk {
	return &TurnCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TurnClient) MapCreateBulk(slice any, setFunc func(*TurnCreate, int)) *TurnCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TurnCreateBulk{err: fmt.Errorf("calling to TurnClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TurnCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TurnCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Turn.
func (c *TurnClient) Update() *TurnUpdate {
	mutation := newTurnMutation(c.config, OpUpdate)
	return &TurnUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TurnClient) UpdateOne(_m *Turn) *TurnUpdateOne {
	mutation := newTurnMutation(c.config, OpUpdateOne, withTurn(_m))
	return &TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TurnClient) UpdateOneID(id int) *TurnUpdateOne {
	mutation := newTurnMutation(c.config, OpUpdateOne, withTurnID(id))
	return &TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Turn.
func (c *TurnClient) Delete() *TurnDelete {
	mutation := newTurnMutation(c.config, OpDelete)
	return &TurnDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TurnClient) DeleteOne(_m *Turn) *TurnDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TurnClient) DeleteOneID(id int) *TurnDeleteOne {
	builder := c.Delete().Where(turn.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TurnDeleteOne{builder}
}

// Query returns a query builder for Turn.
func (c *TurnClient) Query() *TurnQuery {
	return &TurnQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTurn},
		inters: c.Interceptors(),
	}
}

// Get returns a Turn entity by its id.
func (c *TurnClient) Get(ctx context.Context, id int) (*Turn, error) {
	return c.Query().Where(turn.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TurnClient) GetX(ctx context.Context, id int) *Turn {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMetadata queries the metadata edge of a Turn.
func (c *TurnClient) QueryMetadata(_m *Turn) *TurnMetadataQuery {
	query := (&TurnMetadataClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(turn.Table, turn.FieldID, id),
			sqlgraph.To(turnmetadata.Table, turnmetadata.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, turn.MetadataTable, turn.MetadataColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBlocks queries the blocks edge of a Turn.
func (c *TurnClient) QueryBlocks(_m *Turn) *BlockQuery {
	query := (&BlockClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(turn.Table, turn.FieldID, id),
			sqlgraph.To(block.Table, block.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, turn.BlocksTable, turn.BlocksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TurnClient) Hooks() []Hook {
	return c.hooks.Turn
}

// Interceptors returns the client interceptors.
func (c *TurnClient) Interceptors() []Interceptor {
	return c.inters.Turn
}

func (c *TurnClient) mutate(ctx context.Context, m *TurnMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TurnCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TurnUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TurnUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TurnDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Turn mutation op: %q", m.Op())
	}
}

// TurnMetadataClient is a client for the TurnMetadata schema.
type TurnMetadataClient struct {
	config
}

// NewTurnMetadataClient returns a client for the TurnMetadata from the given config.
func NewTurnMetadataClient(c config) *TurnMetadataClient {
	return &TurnMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `turnmetadata.Hooks(f(g(h())))`.
func (c *TurnMetadataClient) Use(hooks ...Hook) {
	c.hooks.TurnMetadata = append(c.hooks.TurnMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `turnmetadata.Intercept(f(g(h())))`.
func (c *TurnMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.TurnMetadata = append(c.inters.TurnMetadata, interceptors...)
}

// Create returns a builder for creating a TurnMetadata entity.
func (c *TurnMetadataClient) Create() *TurnMetadataCreate {
	mutation := newTurnMetadataMutation(c.config, OpCreate)
	return &TurnMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TurnMetadata entities.
func (c *TurnMetadataClient) CreateBulk(builders ...*TurnMetadataCreate) *TurnMetadataCreateBulk {
	return &TurnMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TurnMetadataClient) MapCreateBulk(slice any, setFunc func(*TurnMetadataCreate, int)) *TurnMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TurnMetadataCreateBulk{err: fmt.Errorf("calling to TurnMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TurnMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TurnMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TurnMetadata.
func (c *TurnMetadataClient) Update() *TurnMetadataUpdate {
	mutation := newTurnMetadataMutation(c.config, OpUpdate)
	return &TurnMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TurnMetadataClient) UpdateOne(_m *TurnMetadata) *TurnMetadataUpdateOne {
	mutation := newTurnMetadataMutation(c.config, OpUpdateOne, withTurnMetadata(_m))
	return &TurnMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TurnMetadataClient) UpdateOneID(id int) *TurnMetadataUpdateOne {
	mutation := newTurnMetadataMutation(c.config, OpUpdateOne, withTurnMetadataID(id))
	return &TurnMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TurnMetadata.
func (c *TurnMetadataClient) Delete() *TurnMetadataDelete {
	mutation := newTurnMetadataMutation(c.config, OpDelete)
	return &TurnMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TurnMetadataClient) DeleteOne(_m *TurnMetadata) *TurnMetadataDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TurnMetadataClient) DeleteOneID(id int) *TurnMetadataDeleteOne {
	builder := c.Delete().Where(turnmetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TurnMetadataDeleteOne{builder}
}

// Query returns a query builder for TurnMetadata.
func (c *TurnMetadataClient) Query() *TurnMetadataQuery {
	return &TurnMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTurnMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a TurnMetadata entity by its id.
func (c *TurnMetadataClient) Get(ctx context.Context, id int) (*TurnMetadata, error) {
	return c.Query().Where(turnmetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TurnMetadataClient) GetX(ctx context.Context, id int) *TurnMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTurn queries the turn edge of a TurnMetadata.
func (c *TurnMetadataClient) QueryTurn(_m *TurnMetadata) *TurnQuery {
	query := (&TurnClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(turnmetadata.Table, turnmetadata.FieldID, id),
			sqlgraph.To(turn.Table, turn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, turnmetadata.TurnTable, turnmetadata.TurnColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TurnMetadataClient) Hooks() []Hook {
	return c.hooks.TurnMetadata
}

// Interceptors returns the client interceptors.
func (c *TurnMetadataClient) Interceptors() []Interceptor {
	return c.inters.TurnMetadata
}

func (c *TurnMetadataClient) mutate(ctx context.Context, m *TurnMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TurnMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TurnMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TurnMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TurnMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TurnMetadata mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Block, BlockMetadata, Turn, TurnMetadata []ent.Hook
	}
	inters struct {
		Block, BlockMetadata, Turn, TurnMetadata []ent.Interceptor
	}
)
