// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"turn-inspector/ent/predicate"
	"turn-inspector/ent/runmetadata"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunMetadataDelete is the builder for deleting a RunMetadata entity.
type RunMetadataDelete struct {
	config
	hooks    []Hook
	mutation *RunMetadataMutation
}

// Where appends a list predicates to the RunMetadataDelete builder.
func (_d *RunMetadataDelete) Where(ps ...predicate.RunMetadata) *RunMetadataDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RunMetadataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunMetadataDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RunMetadataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runmetadata.Table, sqlgraph.NewFieldSpec(runmetadata.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RunMetadataDeleteOne is the builder for deleting a single RunMetadata entity.
type RunMetadataDeleteOne struct {
	_d *RunMetadataDelete
}

// Where appends a list predicates to the RunMetadataDelete builder.
func (_d *RunMetadataDeleteOne) Where(ps ...predicate.RunMetadata) *RunMetadataDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RunMetadataDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runmetadata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunMetadataDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
