// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"turn-inspector/ent/turn"
	"turn-inspector/ent/turnmetadata"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TurnMetadataCreate is the builder for creating a TurnMetadata entity.
type TurnMetadataCreate struct {
	config
	mutation *TurnMetadataMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *TurnMetadataCreate) SetSource(v string) *TurnMetadataCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *TurnMetadataCreate) SetKey(v string) *TurnMetadataCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *TurnMetadataCreate) SetValue(v string) *TurnMetadataCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetTurnID sets the "turn" edge to the Turn entity by ID.
func (_c *TurnMetadataCreate) SetTurnID(id int) *TurnMetadataCreate {
	_c.mutation.SetTurnID(id)
	return _c
}

// SetTurn sets the "turn" edge to the Turn entity.
func (_c *TurnMetadataCreate) SetTurn(v *Turn) *TurnMetadataCreate {
	return _c.SetTurnID(v.ID)
}

// Mutation returns the TurnMetadataMutation object of the builder.
func (_c *TurnMetadataCreate) Mutation() *TurnMetadataMutation {
	return _c.mutation
}

// Save creates the TurnMetadata in the database.
func (_c *TurnMetadataCreate) Save(ctx context.Context) (*TurnMetadata, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TurnMetadataCreate) SaveX(ctx context.Context) *TurnMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TurnMetadataCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TurnMetadataCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TurnMetadataCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "TurnMetadata.source"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TurnMetadata.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "TurnMetadata.value"`)}
	}
	if len(_c.mutation.TurnIDs()) == 0 {
		return &ValidationError{Name: "turn", err: errors.New(`ent: missing required edge "TurnMetadata.turn"`)}
	}
	return nil
}

func (_c *TurnMetadataCreate) sqlSave(ctx context.Context) (*TurnMetadata, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TurnMetadataCreate) createSpec() (*TurnMetadata, *sqlgraph.CreateSpec) {
	var (
		_node = &TurnMetadata{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(turnmetadata.Table, sqlgraph.NewFieldSpec(turnmetadata.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(turnmetadata.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(turnmetadata.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(turnmetadata.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := _c.mutation.TurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   turnmetadata.TurnTable,
			Columns: []string{turnmetadata.TurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(turn.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.turn_metadata = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TurnMetadataCreateBulk is the builder for creating many TurnMetadata entities in bulk.
type TurnMetadataCreateBulk struct {
	config
	err      error
	builders []*TurnMetadataCreate
}

// Save creates the TurnMetadata entities in the database.
func (_c *TurnMetadataCreateBulk) Save(ctx context.Context) ([]*TurnMetadata, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TurnMetadata, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TurnMetadataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TurnMetadataCreateBulk) SaveX(ctx context.Context) []*TurnMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TurnMetadataCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TurnMetadataCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
