package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/user/git-precommit-guard/pkg/git"
)

// installCmd represents the install command
var installCmd = &cobra.Command{
	Use:   "install",
	Short: "Install git pre-commit hook",
	Long: `Install the git pre-commit hook in the current repository.

This command creates a pre-commit hook script in .git/hooks/pre-commit that
calls this utility to check staged files before allowing commits.`,
	Run: runInstall,
}

func runInstall(cmd *cobra.Command, args []string) {
	// Check if we're in a git repository
	if !git.IsGitRepository() {
		exitWithError("Not in a git repository")
	}

	// Get repository root
	repoRoot, err := git.GetRepositoryRoot()
	if err != nil {
		exitWithError("Failed to get repository root: %v", err)
	}

	// Create hooks directory if it doesn't exist
	hooksDir := filepath.Join(repoRoot, ".git", "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		exitWithError("Failed to create hooks directory: %v", err)
	}

	// Path to pre-commit hook
	hookPath := filepath.Join(hooksDir, "pre-commit")

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil {
		fmt.Printf("Pre-commit hook already exists at %s\n", hookPath)
		fmt.Println("Do you want to overwrite it? (y/N)")
		
		var response string
		fmt.Scanln(&response)
		if response != "y" && response != "Y" {
			fmt.Println("Installation cancelled")
			return
		}
	}

	// Get the path to this executable
	execPath, err := os.Executable()
	if err != nil {
		exitWithError("Failed to get executable path: %v", err)
	}

	// Create hook script
	hookScript := fmt.Sprintf(`#!/bin/sh
# Git pre-commit hook generated by git-precommit-guard
# This hook runs git-precommit-guard to check staged files

exec "%s" check
`, execPath)

	// Write hook script
	if err := os.WriteFile(hookPath, []byte(hookScript), 0755); err != nil {
		exitWithError("Failed to write hook script: %v", err)
	}

	fmt.Printf("Successfully installed pre-commit hook at %s\n", hookPath)
	fmt.Println("\nThe hook will now run automatically before each commit.")
	fmt.Println("To bypass the hook for a specific commit, use: git commit --no-verify")
}

