package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-go-golems/glazed/pkg/cli"
	"github.com/go-go-golems/glazed/pkg/cmds"
	"github.com/go-go-golems/glazed/pkg/cmds/layers"
	"github.com/pkg/errors"

	gitpkg "github.com/user/git-precommit-guard/pkg/git"
)

// InstallCommand implements the dual-mode install command
 type InstallCommand struct {
	*cmds.CommandDescription
}

// InstallSettings currently unused
 type InstallSettings struct{}

// NewInstallCommand constructs the Glazed command description
 func NewInstallCommand() (*InstallCommand, error) {
	commandSettingsLayer, err := cli.NewCommandSettingsLayer()
	if err != nil {
		return nil, errors.Wrap(err, "create command settings layer")
	}

	cd := cmds.NewCommandDescription(
		"install",
		cmds.WithShort("Install git pre-commit hook"),
		cmds.WithLong(`Install the git pre-commit hook in the current repository.

This command creates a pre-commit hook script in .git/hooks/pre-commit that
calls this utility to check staged files before allowing commits.`),
		cmds.WithLayersList(commandSettingsLayer),
	)

	return &InstallCommand{CommandDescription: cd}, nil
}

// Run is the human-readable mode
 func (c *InstallCommand) Run(ctx context.Context, pl *layers.ParsedLayers) error {
	if !gitpkg.IsGitRepository() {
		return errors.New("not in a git repository")
	}

	gitDir, err := gitpkg.GetGitDir()
	if err != nil {
		return errors.Wrap(err, "get git dir")
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return errors.Wrap(err, "create hooks directory")
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")
	if _, err := os.Stat(hookPath); err == nil {
		fmt.Printf("Pre-commit hook already exists at %s\n", hookPath)
		fmt.Println("Do you want to overwrite it? (y/N)")
		var response string
		fmt.Scanln(&response)
		if !strings.EqualFold(response, "y") {
			fmt.Println("Installation cancelled")
			return nil
		}
	}

	execPath, err := os.Executable()
	if err != nil {
		return errors.Wrap(err, "get executable path")
	}

	hookScript := fmt.Sprintf(`#!/bin/sh
# Git pre-commit hook generated by git-precommit-guard
# This hook runs git-precommit-guard to check staged files

exec "%s" check
`, execPath)

	if err := os.WriteFile(hookPath, []byte(hookScript), 0755); err != nil {
		return errors.Wrap(err, "write hook script")
	}

	fmt.Printf("Successfully installed pre-commit hook at %s\n", hookPath)
	fmt.Println("\nThe hook will now run automatically before each commit.")
	fmt.Println("To bypass the hook for a specific commit, use: git commit --no-verify")
	return nil
}


var _ cmds.BareCommand = &InstallCommand{}

